/* GENERATED by src/room/assets/audio/build-audio.mjs — do not edit.
 *
 * 2015 clips, 41.5 MB, 140 minutes.
 *
 * A SUMMARY, never the index and never audio. The index is
 * `public/audio/index.json` (39 kB), fetched by `bank.ts` the
 * first time a cue asks for a clip; the audio is
 * `public/audio/<type>/<name>.mp3`, fetched one clip at a time, on first use,
 * and cached.
 *
 * THIS FILE IS THE ONLY PART OF THE PACK ON THE FIRST-PAINT PATH, which is why
 * it is a handful of numbers and nothing else. `GameAudio` reads it at the app
 * root to decide whether to draw a voice fader, and that is all it is for. The
 * per-line listing a test would want is in the sibling `lines.generated.ts`,
 * which the app never imports.
 *
 * See `provenance.json` for what these recordings are and whose decision it was
 * to ship them.
 */

export interface PackSummary {
  /** Index format `bank.ts` understands. */
  readonly version: number;
  /** Content stamp, sent as `?v=` on every fetch so a rebuild is never stale. */
  readonly stamp: string;
  readonly clips: number;
  readonly bytes: number;
  readonly seconds: number;
  readonly roles: Readonly<Record<string, { readonly n: number; readonly bytes: number }>>;
}

export const PACK: PackSummary | null = {
  "version": 1,
  "stamp": "0631bc4fc2",
  "clips": 2015,
  "bytes": 43464096,
  "seconds": 8410,
  "roles": {
    "sfx": {
      "n": 52,
      "bytes": 527436
    },
    "line": {
      "n": 42,
      "bytes": 274536
    },
    "voice": {
      "n": 1920,
      "bytes": 41774220
    },
    "music": {
      "n": 1,
      "bytes": 887904
    }
  }
};
