/* GENERATED by src/room/assets/audio/build-audio.mjs — do not edit.
 *
 * empty. no clip ships: every sound is synthesised — see provenance.json
 *
 * An INDEX, never audio: whatever is listed here lives in `public/audio/` and is
 * fetched the first time a cue asks for it. An empty index is a working game —
 * every cue carries a synthesised patch (`sfx.ts`, `generative.ts`) and a clip
 * is only ever preferred over it, never required by it.
 *
 * Keys are the engine's own sound paths with the extension dropped, because that
 * is the shape `LogEvent{PlaySound}` puts on the wire.
 */

/** What a clip is for. Decides its bus, its volume and whether it may be cut off. */
export type ClipRole = 'music' | 'sfx' | 'voice';

export interface Clip {
  /** Engine sound path, no extension: `audio/system/chain`. */
  readonly key: string;
  /** Filename under `public/audio/`. */
  readonly file: string;
  readonly role: ClipRole;
  readonly bytes: number;
  readonly seconds: number;
}

export const CLIPS: readonly Clip[] = [];

export const CLIP_BY_KEY: ReadonlyMap<string, Clip> = new Map(CLIPS.map((c) => [c.key, c]));
