// GENERATED by src/room/skins/generate.mjs -- do not edit by hand.
//
// Source: packages/lunarltk_skins (GPL-3.0 Lua) against 7 engine packages.
// 110 shipped generals, 226 artwork files (88 static, 138 video).
// Artwork is fetched at runtime from: cdn.jsdelivr.net, cnb.cool.
// URLs are percent-encoded; skin display names are omitted (see generate.mjs).
// See index.ts in this directory for the licensing and privacy position.
import type { SkinEntry } from './types';

export const SKIN_CATALOG: Readonly<Record<string, readonly SkinEntry[]>> = {
  "caocao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caocao_dihuangkaijia.jpg" },
  ],
  "caochun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caochun_zhuiwangzhubei.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caochun_shuohuxianfeng.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caochun_huxiaolongyuan.mp4" },
  ],
  "daqiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/daqiao_huizhilanxin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/daqiao_chunhuaifuqing.jpg" },
  ],
  "diaochan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_taotaolejin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_wuhuoqunxin.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sp__diaochan_huandieyinghun.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_qiushuiyiren.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E8%B2%82%E8%9D%89--%E7%A7%8B%E6%B0%B4%E4%BC%8A%E4%BA%BA.mp4" },
  ],
  "godguojia": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godguojia_yixinzheyue.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godguojia_yixinzheyue2.mp4" },
  ],
  "godhuatuo": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E7%A5%9E%E5%8D%8E%E4%BD%97%E3%80%81%E9%95%BF%E5%A4%9C%E5%90%AF%E6%98%8E.jpg" },
  ],
  "godlusu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godlusu_jiuzhouweiju.jpg" },
  ],
  "godsunce": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godsunce_fuhaifanjiang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godsunce_bawangzaishi.mp4" },
  ],
  "godtaishici": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godtaishici_yonghanriyue.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godtaishici_wanmodangchu.jpg" },
  ],
  "godxunyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godxunyu_kuanghanyanzuo.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godxunyu_weihanjianan.mp4" },
  ],
  "guansuo": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%85%B3%E7%B4%A2%E3%80%81%E5%85%94%E5%A8%87%E6%98%A5%E6%B5%93.mp4" },
  ],
  "guanyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guanyu_yuzhuobushi.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guanyu_dandaofuhui.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guanyu_longshengjiuzi.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guanyu_shengchuiqiangu2.jpg" },
  ],
  "guojia": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guojia_yishenzhengdao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guojia_modianjiangshan.mp4" },
  ],
  "huanggai": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huanggai_hubenguanyong.jpg" },
  ],
  "huangyueying": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_zhifeiqiaohui.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_zhengmianduijue.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_miaoxiangshenji.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_muniuliuma.mp4" },
  ],
  "hujinding": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/hujinding_qingjitaoyao.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/hujinding_diejianchunfeng.mp4" },
  ],
  "jiangwan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/jiangwan_chengjiyufeng.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/jiangwan_huguoanmin.jpg" },
  ],
  "liubei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liubei_manianxianding.mp4" },
  ],
  "m_ex__bulianshi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/bulianshi_bieheguluan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/bulianshi_qiushuiyiren.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E6%AD%A5%E7%BB%83%E5%B8%88%E3%80%81%E7%BB%98%E9%B8%A2%E9%BB%9B%E6%83%85.mp4" },
  ],
  "m_ex__caifuren": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caifuren_jinyuxunxin.jpg" },
  ],
  "m_ex__caiwenji": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caiwenji_yishenzhengdao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caiwenji_qiushuiyiren.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E8%94%A1%E6%96%87%E5%A7%AC--%E5%AF%92%E6%9C%88%E4%BB%99%E8%B8%AA.mp4" },
  ],
  "m_ex__caopi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_dangranyouxin.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_longnianzhongqiu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_weiwangchengdi.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_jiuzuiyeqing.jpg" },
  ],
  "m_ex__caozhi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caozhi_qibujuezhang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caozhi_longnianzhongqiu.mp4" },
  ],
  "m_ex__dengai": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dengai_bingxiamianzhu.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dengai_jizhanbenxian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%82%93%E8%89%BE%E3%80%81%E7%A5%9E%E5%85%B5%E5%A4%A9%E9%99%8D.jpg" },
  ],
  "m_ex__dianwei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dianwei_zhihuoshuojin.jpg" },
  ],
  "m_ex__gaoshun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/gaoshun_cuifengdangyu.jpg" },
  ],
  "m_ex__jvshou": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/jvshou_luodingtianyuan.mp4" },
  ],
  "m_ex__liru": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liru_lieyanzhihun.jpg" },
  ],
  "m_ex__liubiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liubiao_jingxianggushou.jpg" },
  ],
  "m_ex__pangtong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/pangtong_duoshuai.jpg" },
  ],
  "m_ex__sunluban": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunluban_jinzhiyuye.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunluban_yuanchaixianglan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E9%B2%81%E7%8F%AD%E3%80%81%E7%8E%89%E9%A2%9C%E5%8F%8C%E5%A8%87.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%AD%99%E9%B2%81%E7%8F%AD--%E6%95%95%E5%B9%BD%E6%98%8E.mp4" },
  ],
  "m_ex__weiyan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/weiyan_yanlongkaijia.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyuan_shuofengduzhi.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E9%AD%8F%E5%BB%B6--%E8%AA%93%E6%AD%BB%E5%8D%AB%E6%B1%89.mp4" },
  ],
  "m_ex__wolong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wolong_qiruojinlan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wolong_lieyanzhihun.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wolong_huichishanhe.jpg" },
  ],
  "m_ex__wuguotai": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%90%B4%E5%9B%BD%E5%A4%AA--%E9%87%91%E7%A7%8B%E7%8E%89%E9%9C%B2.mp4" },
  ],
  "m_ex__xiaoqiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xiaoqiao_lizhitiancheng.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%B0%8F%E4%B9%94--%E6%A1%82%E6%A2%A6%E5%BC%A6%E6%AD%8C.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%B0%8F%E4%B9%94--%E8%8A%B1%E5%A5%BD%E6%9C%88%E5%9C%86.mp4" },
  ],
  "m_ex__xuhuang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xuhuang_dangkouzhuojun.jpg" },
  ],
  "m_ex__xunyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%8D%80%E5%BD%A7%E3%80%81%E6%9D%BE%E9%9F%B5%E9%BE%99%E7%BF%94.jpg" },
  ],
  "m_ex__xusheng": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/ol_ex__xusheng_pojunshajiang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xusheng_caodaobige.mp4" },
  ],
  "m_ex__zhonghui": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhonghui_zhongxiangguipu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhonghui_longshenjiuzi.jpg" },
  ],
  "m_ex__zhoufei": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A6%83--%E7%A2%A7%E9%87%8E%E7%AE%9C%E5%A3%B0.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A6%83--%E9%87%91%E6%9E%9D%E7%8E%89%E5%8F%B6.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A6%83--%E7%AC%BC%E4%B8%AD%E7%AE%9C%E5%93%8D.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A6%83--%E9%B9%8A%E6%8B%BE%E5%A4%95%E6%83%85.mp4" },
  ],
  "m_ex__zhuran": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhuran_bingranwuju.mp4" },
  ],
  "m_friend__xushu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_friend__xushu_zuilikanjian.jpg" },
  ],
  "m_friend__zhugeliang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_friend__zhugeliang_mengzhenqianqiu.jpg" },
  ],
  "m_liuyi__zhouyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mu__zhouyu_lehewanzhao.jpg" },
  ],
  "m_shi2__weiyan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_shi2__weiyan_kuangzhituntian.mp4" },
  ],
  "m_shi3__weiyan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_shi3__weiyan_kuangzhituntian.mp4" },
  ],
  "m_shi__dengai": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dengai_bingxiamianzhu.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dengai_jizhanbenxian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%82%93%E8%89%BE%E3%80%81%E7%A5%9E%E5%85%B5%E5%A4%A9%E9%99%8D.jpg" },
  ],
  "m_shi__huanjie": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%8A%BF%E6%A1%93%E9%98%B6%E3%80%81%E5%AE%9A%E8%AE%A1%E8%B0%8B%E5%9B%BD.jpg" },
  ],
  "m_shi__lusu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/lusu_dangranyouxin.jpg" },
  ],
  "m_shi__luyusheng": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E9%99%86%E9%83%81%E7%94%9F--%E7%B4%A0%E5%BF%83%E5%82%B2%E9%9B%AA.mp4" },
  ],
  "m_shi__sunchen": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%AD%99%E7%B6%9D--%E8%9A%BA%E5%BD%B1%E7%BC%9A%E5%A4%A9.mp4" },
  ],
  "m_shi__taishici": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_shi__taishici_yilingwanxiang.mp4" },
  ],
  "m_shi__weiyan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_shi__weiyan_kuangzhituntian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/weiyan_yanlongkaijia.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyuan_shuofengduzhi.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E9%AD%8F%E5%BB%B6--%E8%AA%93%E6%AD%BB%E5%8D%AB%E6%B1%89.mp4" },
  ],
  "m_shi__xinxianying": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xinxianying_fengzhuluanhui.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xinxianying_jinxiudaimei.mp4" },
  ],
  "m_shi__yuji": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_shi__yuji_xingquanjingfu.jpg" },
  ],
  "m_shi__zhonghui": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_shi__zhonghui_qianjiaojitian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_shi__zhonghui_qianjiaojitian2.mp4" },
  ],
  "m_sp__caocao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caocao_dihuangkaijia.jpg" },
  ],
  "m_sp__simazhao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_zhaoweihuainan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_denglujiemian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_longxuexuanhuang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_zhaosuyuanxin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_yongduokuishou.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_wenqingliangyuan.jpg" },
  ],
  "m_thoroughbred__zhangliao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangliao_longshengjiuzi.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangliao_benleipozhen.jpg" },
  ],
  "m_yuan__gaoshun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/gaoshun_cuifengdangyu.jpg" },
  ],
  "m_yuan__sunquan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunquan_songcuichangqing.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E6%9D%83%E3%80%81%E7%BB%98%E9%B8%A2%E9%BB%9B%E6%83%85.mp4" },
  ],
  "mazhong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mazhong_gangfengzhuokou.jpg" },
  ],
  "mobile2__caomao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mobile2__caomao_xiaolongpoyuan.mp4" },
  ],
  "mobile__baosanniang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/baosanniang_tujiaochunnong.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/baosanniang_satafeishuang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/baosanniang_shenqinggujian.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/images/baosanniang_yanranyixiao.mp4" },
  ],
  "mobile__baoxin": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/baoxin_guanjuetianxia.mp4" },
  ],
  "mobile__bianfuren": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/ol__bianfuren_yindaizhuangmei.mp4" },
  ],
  "mobile__caomao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mobile__caomao_xiaolongpoyuan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caomao_longxuexuanhuang.mp4" },
  ],
  "mobile__caosong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mobile__caosong_yanyinggaopeng.jpg" },
  ],
  "mobile__caoying": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoying_changyelinxi.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoying_baiquemingchen.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoying_shuiqingzhuoying.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoying_weiyingfengming.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E6%9B%B9%E5%A9%B4--%E9%AD%8F%E6%AD%A6%E9%81%97%E9%A3%8E.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E6%9B%B9%E5%A9%B4--%E6%B5%81%E7%BB%AF%E6%83%8A%E6%BE%9C.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E6%9B%B9%E5%A9%B4--%E6%B0%B4%E6%B8%85%E6%BF%AF%E7%BC%A8.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/images/caoying_jinzhiyuye.mp4" },
  ],
  "mobile__chengui": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/chengui_zhanchangrongyao.mp4" },
  ],
  "mobile__duyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/duyu_yulinbilang.jpg" },
  ],
  "mobile__ganfuren": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E7%94%98%E5%A4%AB%E4%BA%BA--%E4%B9%9E%E5%B7%A7%E6%83%85.mp4" },
  ],
  "mobile__godjiangwei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mobile__godjiangwei_jianyintianlin.mp4" },
  ],
  "mobile__godmachao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godmachao_xunwujinglei.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godmachao_madaogongcheng.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godmachao_leizhuafucang.mp4" },
  ],
  "mobile__godsimayi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godsimayi_jianwangzhilai.mp4" },
  ],
  "mobile__guanyinping": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%85%B3%E9%93%B6%E5%B1%8F--%E7%83%88%E7%84%B0%E7%82%BD%E9%AD%82.mp4" },
  ],
  "mobile__guozhao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mobile__guozhao_quehanjingfeng.mp4" },
  ],
  "mobile__huaman": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mobile__huaman_lingxiufeiyin.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E8%8A%B1%E9%AC%98--%E6%B2%99%E5%9C%BA%E8%9B%AE%E8%8A%B1.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E8%8A%B1%E9%AC%98--%E4%BE%9D%E5%BF%83%E7%BC%B1%E7%BB%BB.mp4" },
  ],
  "mobile__lingju": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/lingju_xueyingposuo.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/images/lingju_hunqiangmengying.mp4" },
  ],
  "mobile__liuye": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/ol__liuye_fenyantianzheng.mp4" },
  ],
  "mobile__maliang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/maliang_dangranyouxin.mp4" },
  ],
  "mobile__qinghegongzhu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/qinghegongzhu_xinxiangqinghuan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/qinghegongzhu_meiyingyingxin.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/qinghegongzhu_yufeiqionghua.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/qinghegongzhu_qingyaqudou.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/qinghegongzhu_wuyinliyan.mp4" },
  ],
  "mobile__simazhao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_zhaoweihuainan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_denglujiemian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_longxuexuanhuang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_zhaosuyuanxin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_yongduokuishou.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_wenqingliangyuan.jpg" },
  ],
  "mobile__sunluyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunluyu_huweibobing.jpg" },
  ],
  "mobile__wangyuanji": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wangyuanji_dieyingpianqian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wangyuanji_wenqingliangyuan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wangyuanji_caiyimanwu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wangyuanji_posuoqiwu.mp4" },
  ],
  "mobile__wenyang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyang_wu_poyukaitian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyang_wei_poyukaitian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyang_shiruowanjun.mp4" },
  ],
  "mobile__xurong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xurong_nuliaohengkong.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xurong_nuliaohengkong2.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xurong_lieyanzhihun.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xurong_zhanhuotianjue.mp4" },
  ],
  "mobile__yanghu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/ol__yanghu_qingshangyimeng.jpg" },
  ],
  "mobile__yanghuiyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yanghuiyu_sheniankuanghuan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yanghuiyu_jingyuhehui.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yanghuiyu_yueyaohuashang.mp4" },
  ],
  "mobile__zhangchangpu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangchangpu_zhanchangrongyao.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%BC%A0%E6%98%8C%E8%92%B2%E3%80%81%E5%B1%B1%E6%B2%B3%E4%B8%87%E6%9C%B5.jpg" },
  ],
  "mobile__zhangfen": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangfen_bihaihanshan.jpg" },
  ],
  "mobile__zhangqiying": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangqiying_lianyanqingfang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangqiying_suirennianfeng.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/images/zhangqiying_jiyufengnian.mp4" },
  ],
  "mobile__zhouchu": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A4%84--%E4%B9%89%E9%99%A4%E4%B8%89%E5%AE%B3-%E5%90%B4.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A4%84--%E6%93%92%E8%99%8E%E6%8B%BF%E8%9B%9F.mp4" },
  ],
  "mouxusheng": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xusheng_caodaobige.mp4" },
  ],
  "mxing__fazheng": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/fazheng_fengguqingyu.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/fazheng_weijiguangsha.jpg" },
  ],
  "mxing__huangzhong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangzhong_liejianguanyun.jpg" },
  ],
  "mxing__weiyan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/weiyan_yanlongkaijia.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyuan_shuofengduzhi.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E9%AD%8F%E5%BB%B6--%E8%AA%93%E6%AD%BB%E5%8D%AB%E6%B1%89.mp4" },
  ],
  "nanhualaoxian": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/nanhualaoxian_zhuomoshanhe.jpg" },
  ],
  "nos__xunchen": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xunchen_ximuzhize.jpg" },
  ],
  "simayi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simayi_moudingtianxia.jpg" },
  ],
  "sunquan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunquan_songcuichangqing.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E6%9D%83%E3%80%81%E7%BB%98%E9%B8%A2%E9%BB%9B%E6%83%85.mp4" },
  ],
  "sunru": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunru_mulanhanfang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunru_shenianqingming.mp4" },
  ],
  "sunshangxiang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_niaoyuhuaxiang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_qianhouliangnan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_jiaozoongsanjiang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_jinguoqianying.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%AD%99%E5%B0%9A%E9%A6%99--%E6%88%98%E5%9C%BA%E8%8D%A3%E8%80%80.mp4" },
  ],
  "yangbiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yangbiao_guozhizhushi.mp4" },
  ],
  "zhangliao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangliao_longshengjiuzi.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangliao_benleipozhen.jpg" },
  ],
  "zhaoyun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%B5%B5%E4%BA%91%E3%80%81%E8%9B%87%E5%B9%B4%E4%B8%83%E5%A4%95.mp4" },
  ],
  "zhenji": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_xunitiantuan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_zhanchangjueban.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_qingluoyuelong.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_niunianqingming.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_mingzhuyaoqu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_luoshuishenyun.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_duanruiluoshui.mp4" },
  ],
  "zhouyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhouyu_yaxiangzhenzhu.jpg" },
  ],
  "zhugeguo": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeguo_jinzhiyuye.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeguo_qiushuiyiren.mp4" },
  ],
  "zhugeliang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_yizhenqingmeng.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_shanhewuyang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_guozhizhushi.mp4" },
  ],
};

/** Hosts the catalog points at. The circuit breaker keys off these. */
export const SKIN_HOSTS: readonly string[] = ["cdn.jsdelivr.net","cnb.cool"];
