// GENERATED by src/room/skins/generate.mjs -- do not edit by hand.
//
// Source: src/room/skins/pack (lunarltk_skins, GPL-3.0 Lua) booted with the shipped
// roster: standard, standard_cards, maneuvering, test, utility, mobile, standard_ex, shzl, yj, sp, mougong, jsrg, sxrm, webmodes.
// 305 shipped generals (280 in the playable pool), 684 artwork files (284 static, 400 video).
// Artwork is fetched at runtime from: cdn.jsdelivr.net, cnb.cool.
// URLs are percent-encoded; skin display names are omitted (see generate.mjs).
// See index.ts in this directory for the licensing and privacy position.
import type { SkinEntry } from './types';

export const SKIN_CATALOG: Readonly<Record<string, readonly SkinEntry[]>> = {
  "bulianshi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/bulianshi_bieheguluan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/bulianshi_qiushuiyiren.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E6%AD%A5%E7%BB%83%E5%B8%88%E3%80%81%E7%BB%98%E9%B8%A2%E9%BB%9B%E6%83%85.mp4" },
  ],
  "caifuren": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caifuren_jinyuxunxin.jpg" },
  ],
  "caiwenji": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caiwenji_yishenzhengdao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caiwenji_qiushuiyiren.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%94%A1%E6%96%87%E5%A7%AC%E3%80%81%E5%B2%81%E7%BB%88%E5%B9%B4%E5%BA%86.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E8%94%A1%E6%96%87%E5%A7%AC--%E5%AF%92%E6%9C%88%E4%BB%99%E8%B8%AA.mp4" },
  ],
  "caocao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caocao_dihuangkaijia.jpg" },
  ],
  "caochun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caochun_zhuiwangzhubei.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caochun_shuohuxianfeng.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caochun_huxiaolongyuan.mp4" },
  ],
  "caojie": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E6%9B%B9%E8%8A%82--%E5%86%B0%E8%82%8C%E7%8E%89%E6%B4%81.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E6%9B%B9%E8%8A%82--%E5%87%B0%E6%B1%89%E6%A2%A6%E5%9B%9E.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E6%9B%B9%E8%8A%82--%E6%B4%BE%E8%8D%AF%E6%B2%BB%E4%BC%A4.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E6%9B%B9%E8%8A%82--%E7%91%9E%E9%9B%AA%E4%B8%B0%E5%B9%B4.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E6%9B%B9%E8%8A%82--%E9%BE%99%E5%B9%B4%E4%B8%AD%E7%A7%8B.mp4" },
  ],
  "caopi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_dangranyouxin.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_longnianzhongqiu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_weiwangchengdi.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_jiuzuiyeqing.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E6%9B%B9%E4%B8%95%E3%80%81%E5%A8%81%E5%BE%A1%E4%B9%9D%E9%9C%84.jpg" },
  ],
  "caoren": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoren_shusijushou.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoren_duoshuai.jpg" },
  ],
  "caoxiu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoxiu_qingfengxilie.jpg" },
  ],
  "caozhi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caozhi_qibujuezhang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caozhi_longnianzhongqiu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E6%9B%B9%E6%A4%8D%E3%80%81%E9%BE%99%E7%94%9F%E4%B9%9D%E5%AD%90.jpg" },
  ],
  "daqiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/daqiao_huizhilanxin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/daqiao_chunhuaifuqing.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%A4%A7%E4%B9%94%E3%80%81%E6%B8%85%E8%90%A7%E6%B8%85%E4%B8%BD.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%A4%A7%E4%B9%94%E3%80%81%E8%8A%B1%E5%80%9A%E8%BD%BB%E6%B6%9F.jpg" },
  ],
  "dengai": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dengai_bingxiamianzhu.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dengai_jizhanbenxian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%82%93%E8%89%BE%E3%80%81%E7%A5%9E%E5%85%B5%E5%A4%A9%E9%99%8D.jpg" },
  ],
  "dianwei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dianwei_zhihuoshuojin.jpg" },
  ],
  "diaochan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_taotaolejin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_wuhuoqunxin.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sp__diaochan_huandieyinghun.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_qiushuiyiren.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%B2%82%E8%9D%89%E3%80%81%E5%87%BA%E6%B0%B4%E5%A6%82%E6%9C%88.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E8%B2%82%E8%9D%89--%E7%A7%8B%E6%B0%B4%E4%BC%8A%E4%BA%BA.mp4" },
  ],
  "dingyuan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E4%B8%81%E5%8E%9F%E3%80%81%E9%BE%99%E8%85%BE%E5%AF%B0%E5%AE%87.mp4" },
  ],
  "ex__caocao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caocao_dihuangkaijia.jpg" },
  ],
  "ex__daqiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/daqiao_huizhilanxin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/daqiao_chunhuaifuqing.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%A4%A7%E4%B9%94%E3%80%81%E6%B8%85%E8%90%A7%E6%B8%85%E4%B8%BD.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%A4%A7%E4%B9%94%E3%80%81%E8%8A%B1%E5%80%9A%E8%BD%BB%E6%B6%9F.jpg" },
  ],
  "ex__diaochan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_taotaolejin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_wuhuoqunxin.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sp__diaochan_huandieyinghun.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_qiushuiyiren.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%B2%82%E8%9D%89%E3%80%81%E5%87%BA%E6%B0%B4%E5%A6%82%E6%9C%88.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E8%B2%82%E8%9D%89--%E7%A7%8B%E6%B0%B4%E4%BC%8A%E4%BA%BA.mp4" },
  ],
  "ex__guanyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guanyu_yuzhuobushi.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guanyu_dandaofuhui.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guanyu_longshengjiuzi.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guanyu_shengchuiqiangu2.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%85%B3%E7%BE%BD%E3%80%81%E5%9C%A3%E4%BB%81%E6%AD%A6%E4%B9%89.jpg" },
  ],
  "ex__guojia": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guojia_yishenzhengdao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guojia_modianjiangshan.mp4" },
  ],
  "ex__huanggai": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huanggai_hubenguanyong.jpg" },
  ],
  "ex__huangyueying": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_zhifeiqiaohui.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_zhengmianduijue.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_miaoxiangshenji.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_muniuliuma.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%BB%84%E6%9C%88%E8%8B%B1%E3%80%81%E6%98%8E%E8%89%AF%E5%8D%83%E5%8F%A4.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%BB%84%E6%9C%88%E8%8B%B1%E3%80%81%E6%99%BA%E5%BF%83%E5%B7%A7%E6%89%8B.mp4" },
  ],
  "ex__liubei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liubei_manianxianding.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%88%98%E5%A4%87%E3%80%81%E5%85%AD%E6%98%9F%E8%80%80%E5%B8%9D.mp4" },
  ],
  "ex__simayi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simayi_moudingtianxia.jpg" },
  ],
  "ex__sunquan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunquan_songcuichangqing.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E6%9D%83%E3%80%81%E5%90%B4%E7%8E%8B%E5%85%AD%E5%89%91.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E6%9D%83%E3%80%81%E7%BB%98%E9%B8%A2%E9%BB%9B%E6%83%85.mp4" },
  ],
  "ex__sunshangxiang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_niaoyuhuaxiang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_qianhouliangnan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_jiaozoongsanjiang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_jinguoqianying.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E5%B0%9A%E9%A6%99%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%AD%99%E5%B0%9A%E9%A6%99--%E6%88%98%E5%9C%BA%E8%8D%A3%E8%80%80.mp4" },
  ],
  "ex__zhangliao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangliao_longshengjiuzi.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangliao_benleipozhen.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%AD%8F%E5%BC%A0%E8%BE%BD%E3%80%81%E9%98%B5%E6%96%A9%E8%B9%8B%E9%A1%BF.jpg" },
  ],
  "ex__zhaoyun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%B5%B5%E4%BA%91%E3%80%81%E8%9B%87%E5%B9%B4%E4%B8%83%E5%A4%95.mp4" },
  ],
  "ex__zhenji": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_xunitiantuan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_zhanchangjueban.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_qingluoyuelong.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_niunianqingming.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_mingzhuyaoqu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_luoshuishenyun.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_duanruiluoshui.mp4" },
  ],
  "ex__zhouyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhouyu_yaxiangzhenzhu.jpg" },
  ],
  "ex__zhugeliang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_yizhenqingmeng.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_shanhewuyang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_guozhizhushi.mp4" },
  ],
  "fazheng": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/fazheng_fengguqingyu.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/fazheng_weijiguangsha.jpg" },
  ],
  "ganfuren": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E7%94%98%E5%A4%AB%E4%BA%BA--%E4%B9%9E%E5%B7%A7%E6%83%85.mp4" },
  ],
  "gaoshun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/gaoshun_cuifengdangyu.jpg" },
  ],
  "godganning": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godganning_zhanpowujian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godganning_shenweirumang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godganning_wanrenbiyi.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godganning_zhanchangrongyao.mp4" },
  ],
  "godguojia": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godguojia_yixinzheyue.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godguojia_yixinzheyue2.mp4" },
  ],
  "godhuatuo": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E7%A5%9E%E5%8D%8E%E4%BD%97%E3%80%81%E9%95%BF%E5%A4%9C%E5%90%AF%E6%98%8E.jpg" },
  ],
  "godlusu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godlusu_jiuzhouweiju.jpg" },
  ],
  "godluxun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godluxun_zhanhuofengwei.jpg" },
  ],
  "godlvbu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godlvbu_guanjuefeijiang.mp4" },
  ],
  "godsimayi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godsimayi_jianwangzhilai.mp4" },
  ],
  "godsunce": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godsunce_fuhaifanjiang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godsunce_bawangzaishi.mp4" },
  ],
  "godtaishici": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godtaishici_yonghanriyue.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godtaishici_wanmodangchu.jpg" },
  ],
  "godxunyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godxunyu_kuanghanyanzuo.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godxunyu_weihanjianan.mp4" },
  ],
  "godzhaoyun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godzhaoyun_linzhenjiuxiao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godzhaoyun_zhanlongzaiye.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godzhaoyun_longtenghuyue.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godzhaoyun_baizhanjinjia.mp4" },
  ],
  "guansuo": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%85%B3%E7%B4%A2%E3%80%81%E5%85%94%E5%A8%87%E6%98%A5%E6%B5%93.mp4" },
  ],
  "guanyinping": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%85%B3%E9%93%B6%E5%B1%8F%E3%80%81%E5%87%A4%E5%B1%8F%E9%93%B6%E6%9C%88.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%85%B3%E9%93%B6%E5%B1%8F--%E7%83%88%E7%84%B0%E7%82%BD%E9%AD%82.mp4" },
  ],
  "guanyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guanyu_yuzhuobushi.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guanyu_dandaofuhui.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guanyu_longshengjiuzi.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guanyu_shengchuiqiangu2.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%85%B3%E7%BE%BD%E3%80%81%E5%9C%A3%E4%BB%81%E6%AD%A6%E4%B9%89.jpg" },
  ],
  "guohuai": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%83%AD%E6%B7%AE%E3%80%81%E7%B4%AB%E7%94%B5%E9%9C%86%E5%87%BB.jpg" },
  ],
  "guohuanghou": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E9%83%AD%E7%9A%87%E5%90%8E--%E6%83%85%E9%B9%8A%E7%BA%B7%E9%A3%9E.mp4" },
  ],
  "guojia": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guojia_yishenzhengdao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guojia_modianjiangshan.mp4" },
  ],
  "haozhao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%83%9D%E6%98%AD%E3%80%81%E5%AE%88%E5%9C%9F%E5%8D%AB%E7%96%86.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%83%9D%E6%98%AD%E3%80%81%E6%88%98%E5%9C%BA%E8%8D%A3%E8%80%80.jpg" },
  ],
  "hetaihou": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/hetaihou_zhanchangrongyao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E4%BD%95%E5%A4%AA%E5%90%8E%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
  ],
  "huanggai": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huanggai_hubenguanyong.jpg" },
  ],
  "huanghao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%BB%84%E7%9A%93%E3%80%81%E8%9B%87%E8%9D%8E%E8%9B%8A%E5%BF%83.mp4" },
  ],
  "huangyueying": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_zhifeiqiaohui.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_zhengmianduijue.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_miaoxiangshenji.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_muniuliuma.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%BB%84%E6%9C%88%E8%8B%B1%E3%80%81%E6%98%8E%E8%89%AF%E5%8D%83%E5%8F%A4.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%BB%84%E6%9C%88%E8%8B%B1%E3%80%81%E6%99%BA%E5%BF%83%E5%B7%A7%E6%89%8B.mp4" },
  ],
  "huangzhong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangzhong_liejianguanyun.jpg" },
  ],
  "hujinding": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/hujinding_qingjitaoyao.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/hujinding_diejianchunfeng.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%83%A1%E9%87%91%E5%AE%9A%E3%80%81%E4%BA%91%E6%A2%A6%E6%B6%9F%E6%BC%AA.mp4" },
  ],
  "jiangwan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/jiangwan_chengjiyufeng.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/jiangwan_huguoanmin.jpg" },
  ],
  "jiangwei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%A7%9C%E7%BB%B4%E3%80%81%E6%98%9F%E6%B2%B3%E9%BA%92%E9%BA%9F.jpg" },
  ],
  "jiaxu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/jiaxu_mouluanchangan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/jiaxu_dangranyouxin.mp4" },
  ],
  "js__caocao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caocao_dihuangkaijia.jpg" },
  ],
  "js__caofang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caofang_langjihupo.jpg" },
  ],
  "js__dengai": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dengai_bingxiamianzhu.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dengai_jizhanbenxian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%82%93%E8%89%BE%E3%80%81%E7%A5%9E%E5%85%B5%E5%A4%A9%E9%99%8D.jpg" },
  ],
  "js__guojia": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guojia_yishenzhengdao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guojia_modianjiangshan.mp4" },
  ],
  "js__guozhao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guozhao_ciyuqinghua.mp4" },
  ],
  "js__huangzhong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangzhong_liejianguanyun.jpg" },
  ],
  "js__jiangwei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%A7%9C%E7%BB%B4%E3%80%81%E6%98%9F%E6%B2%B3%E9%BA%92%E9%BA%9F.jpg" },
  ],
  "js__liubei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liubei_manianxianding.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%88%98%E5%A4%87%E3%80%81%E5%85%AD%E6%98%9F%E8%80%80%E5%B8%9D.mp4" },
  ],
  "js__liubiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liubiao_jingxianggushou.jpg" },
  ],
  "js__liuyan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liuyan_jiuxiwending.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liuyan_xiongjuyizhou.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liuyan_longxingshuchuan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liuyan_zhanchangrongyao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liuyan_qiushuangjinfeng.mp4" },
  ],
  "js__liuyong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liuyong_lijiankaichou.jpg" },
  ],
  "js__lukang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/lukang_guozhizhushi.mp4" },
  ],
  "js__nanhualaoxian": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/nanhualaoxian_zhuomoshanhe.jpg" },
  ],
  "js__pangtong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/pangtong_duoshuai.jpg" },
  ],
  "js__simayi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simayi_moudingtianxia.jpg" },
  ],
  "js__simazhao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_zhaoweihuainan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_denglujiemian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_longxuexuanhuang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_zhaosuyuanxin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_yongduokuishou.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_wenqingliangyuan.jpg" },
  ],
  "js__sunjian": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E5%9D%9A%E3%80%81%E6%AD%A6%E7%83%88%E5%BC%80%E7%96%86.jpg" },
  ],
  "js__sunshangxiang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_niaoyuhuaxiang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_qianhouliangnan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_jiaozoongsanjiang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_jinguoqianying.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E5%B0%9A%E9%A6%99%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%AD%99%E5%B0%9A%E9%A6%99--%E6%88%98%E5%9C%BA%E8%8D%A3%E8%80%80.mp4" },
  ],
  "js__wenyang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyang_wu_poyukaitian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyang_wei_poyukaitian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyang_shiruowanjun.mp4" },
  ],
  "js__xushao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xushao_pingshidiaolong.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xushao_fenghuoliantian.jpg" },
  ],
  "js__yangbiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yangbiao_guozhizhushi.mp4" },
  ],
  "js__yuanshao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yuanshao_zhanchangrongyao.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yuanshao_wojianjichu1.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yuanshao_wojianjichu2.jpg" },
  ],
  "js__zhangren": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/tymou__zhangren_xiangfengfuhu.jpg" },
  ],
  "js__zhangxuan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangxuan_meituchunjiao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangxuan_zhanchangyongyao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangxuan_qingluannihuang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%BC%A0%E5%AB%99%E3%80%81%E6%B6%9F%E6%BC%AA%E5%A4%8F%E6%A2%A6.mp4" },
  ],
  "js__zhaoyun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%B5%B5%E4%BA%91%E3%80%81%E8%9B%87%E5%B9%B4%E4%B8%83%E5%A4%95.mp4" },
  ],
  "js__zhugedan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugedan_chouchunjuyi.mp4" },
  ],
  "js__zhugeliang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_yizhenqingmeng.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_shanhewuyang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_guozhizhushi.mp4" },
  ],
  "js__zoushi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/js__zoushi_zhengmianduijue.jpg" },
  ],
  "js_re__guozhao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guozhao_ciyuqinghua.mp4" },
  ],
  "js_re__liubei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liubei_manianxianding.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%88%98%E5%A4%87%E3%80%81%E5%85%AD%E6%98%9F%E8%80%80%E5%B8%9D.mp4" },
  ],
  "js_re__liuyong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liuyong_lijiankaichou.jpg" },
  ],
  "js_re__sunjian": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E5%9D%9A%E3%80%81%E6%AD%A6%E7%83%88%E5%BC%80%E7%96%86.jpg" },
  ],
  "js_re__xushao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xushao_pingshidiaolong.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xushao_fenghuoliantian.jpg" },
  ],
  "jsp__huangyueying": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_zhifeiqiaohui.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_zhengmianduijue.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_miaoxiangshenji.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_muniuliuma.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%BB%84%E6%9C%88%E8%8B%B1%E3%80%81%E6%98%8E%E8%89%AF%E5%8D%83%E5%8F%A4.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%BB%84%E6%9C%88%E8%8B%B1%E3%80%81%E6%99%BA%E5%BF%83%E5%B7%A7%E6%89%8B.mp4" },
  ],
  "jsp__jiangwei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%A7%9C%E7%BB%B4%E3%80%81%E6%98%9F%E6%B2%B3%E9%BA%92%E9%BA%9F.jpg" },
  ],
  "jsp__zhaoyun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sp__zhaoyun_weimingjinxian.mp4" },
  ],
  "jvshou": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/jvshou_luodingtianyuan.mp4" },
  ],
  "lingju": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/lingju_xueyingposuo.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/images/lingju_hunqiangmengying.mp4" },
  ],
  "liru": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liru_lieyanzhihun.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E6%9D%8E%E5%84%92%E3%80%81%E9%B8%A9%E6%9D%80%E5%B0%91%E5%B8%9D.mp4" },
  ],
  "liubei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liubei_manianxianding.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%88%98%E5%A4%87%E3%80%81%E5%85%AD%E6%98%9F%E8%80%80%E5%B8%9D.mp4" },
  ],
  "liubiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liubiao_jingxianggushou.jpg" },
  ],
  "lukang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/lukang_guozhizhushi.mp4" },
  ],
  "lusu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/lusu_dangranyouxin.jpg" },
  ],
  "m_ex__bulianshi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/bulianshi_bieheguluan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/bulianshi_qiushuiyiren.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E6%AD%A5%E7%BB%83%E5%B8%88%E3%80%81%E7%BB%98%E9%B8%A2%E9%BB%9B%E6%83%85.mp4" },
  ],
  "m_ex__caifuren": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caifuren_jinyuxunxin.jpg" },
  ],
  "m_ex__caiwenji": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caiwenji_yishenzhengdao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caiwenji_qiushuiyiren.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%94%A1%E6%96%87%E5%A7%AC%E3%80%81%E5%B2%81%E7%BB%88%E5%B9%B4%E5%BA%86.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E8%94%A1%E6%96%87%E5%A7%AC--%E5%AF%92%E6%9C%88%E4%BB%99%E8%B8%AA.mp4" },
  ],
  "m_ex__caopi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_dangranyouxin.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_longnianzhongqiu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_weiwangchengdi.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_jiuzuiyeqing.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E6%9B%B9%E4%B8%95%E3%80%81%E5%A8%81%E5%BE%A1%E4%B9%9D%E9%9C%84.jpg" },
  ],
  "m_ex__caozhi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caozhi_qibujuezhang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caozhi_longnianzhongqiu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E6%9B%B9%E6%A4%8D%E3%80%81%E9%BE%99%E7%94%9F%E4%B9%9D%E5%AD%90.jpg" },
  ],
  "m_ex__dengai": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dengai_bingxiamianzhu.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dengai_jizhanbenxian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%82%93%E8%89%BE%E3%80%81%E7%A5%9E%E5%85%B5%E5%A4%A9%E9%99%8D.jpg" },
  ],
  "m_ex__dianwei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dianwei_zhihuoshuojin.jpg" },
  ],
  "m_ex__gaoshun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/gaoshun_cuifengdangyu.jpg" },
  ],
  "m_ex__jiangwei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%A7%9C%E7%BB%B4%E3%80%81%E6%98%9F%E6%B2%B3%E9%BA%92%E9%BA%9F.jpg" },
  ],
  "m_ex__jvshou": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/jvshou_luodingtianyuan.mp4" },
  ],
  "m_ex__liru": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liru_lieyanzhihun.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E6%9D%8E%E5%84%92%E3%80%81%E9%B8%A9%E6%9D%80%E5%B0%91%E5%B8%9D.mp4" },
  ],
  "m_ex__liubiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liubiao_jingxianggushou.jpg" },
  ],
  "m_ex__pangtong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/pangtong_duoshuai.jpg" },
  ],
  "m_ex__sunjian": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E5%9D%9A%E3%80%81%E6%AD%A6%E7%83%88%E5%BC%80%E7%96%86.jpg" },
  ],
  "m_ex__sunluban": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunluban_jinzhiyuye.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunluban_yuanchaixianglan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E9%B2%81%E7%8F%AD%E3%80%81%E7%89%9B%E5%B9%B4%E7%AB%AF%E5%8D%88.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E9%B2%81%E7%8F%AD%E3%80%81%E7%8E%89%E9%A2%9C%E5%8F%8C%E5%A8%87.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%AD%99%E9%B2%81%E7%8F%AD--%E6%95%95%E5%B9%BD%E6%98%8E.mp4" },
  ],
  "m_ex__weiyan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/weiyan_yanlongkaijia.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyuan_shuofengduzhi.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E9%AD%8F%E5%BB%B6--%E8%AA%93%E6%AD%BB%E5%8D%AB%E6%B1%89.mp4" },
  ],
  "m_ex__wolong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wolong_qiruojinlan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wolong_lieyanzhihun.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wolong_huichishanhe.jpg" },
  ],
  "m_ex__wuguotai": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%90%B4%E5%9B%BD%E5%A4%AA--%E9%87%91%E7%A7%8B%E7%8E%89%E9%9C%B2.mp4" },
  ],
  "m_ex__xiaoqiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xiaoqiao_lizhitiancheng.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%B0%8F%E4%B9%94%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%B0%8F%E4%B9%94%E3%80%81%E9%87%87%E8%8E%B2%E6%B1%9F%E5%8D%97.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%B0%8F%E4%B9%94--%E6%A1%82%E6%A2%A6%E5%BC%A6%E6%AD%8C.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%B0%8F%E4%B9%94--%E8%8A%B1%E5%A5%BD%E6%9C%88%E5%9C%86.mp4" },
  ],
  "m_ex__xuhuang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xuhuang_dangkouzhuojun.jpg" },
  ],
  "m_ex__xunyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%8D%80%E5%BD%A7%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%8D%80%E5%BD%A7%E3%80%81%E6%9D%BE%E9%9F%B5%E9%BE%99%E7%BF%94.jpg" },
  ],
  "m_ex__xusheng": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/ol_ex__xusheng_pojunshajiang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xusheng_caodaobige.mp4" },
  ],
  "m_ex__yuanshu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%A2%81%E6%9C%AF%E3%80%81%E7%99%BB%E6%9E%81%E8%87%B3%E5%B0%8A.mp4" },
  ],
  "m_ex__zhonghui": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhonghui_zhongxiangguipu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhonghui_longshenjiuzi.jpg" },
  ],
  "m_ex__zhoufei": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A6%83--%E7%A2%A7%E9%87%8E%E7%AE%9C%E5%A3%B0.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A6%83--%E7%AC%BC%E4%B8%AD%E7%AE%9C%E5%93%8D.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A6%83--%E9%87%91%E6%9E%9D%E7%8E%89%E5%8F%B6.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A6%83--%E9%B9%8A%E6%8B%BE%E5%A4%95%E6%83%85.mp4" },
  ],
  "m_ex__zhuran": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhuran_bingranwuju.mp4" },
  ],
  "m_friend__xushu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_friend__xushu_zuilikanjian.jpg" },
  ],
  "m_friend__zhugeliang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_friend__zhugeliang_mengzhenqianqiu.jpg" },
  ],
  "m_js__sunjian": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E5%9D%9A%E3%80%81%E6%AD%A6%E7%83%88%E5%BC%80%E7%96%86.jpg" },
  ],
  "m_liuyi__zhouyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mu__zhouyu_lehewanzhao.jpg" },
  ],
  "m_shi2__weiyan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_shi2__weiyan_kuangzhituntian.mp4" },
  ],
  "m_shi3__weiyan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_shi3__weiyan_kuangzhituntian.mp4" },
  ],
  "m_shi__dengai": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dengai_bingxiamianzhu.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/dengai_jizhanbenxian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%82%93%E8%89%BE%E3%80%81%E7%A5%9E%E5%85%B5%E5%A4%A9%E9%99%8D.jpg" },
  ],
  "m_shi__huanjie": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%8A%BF%E6%A1%93%E9%98%B6%E3%80%81%E5%AE%9A%E8%AE%A1%E8%B0%8B%E5%9B%BD.jpg" },
  ],
  "m_shi__lusu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/lusu_dangranyouxin.jpg" },
  ],
  "m_shi__luyusheng": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E9%99%86%E9%83%81%E7%94%9F--%E7%B4%A0%E5%BF%83%E5%82%B2%E9%9B%AA.mp4" },
  ],
  "m_shi__sunchen": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%AD%99%E7%B6%9D--%E8%9A%BA%E5%BD%B1%E7%BC%9A%E5%A4%A9.mp4" },
  ],
  "m_shi__taishici": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_shi__taishici_yilingwanxiang.mp4" },
  ],
  "m_shi__weiyan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_shi__weiyan_kuangzhituntian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/weiyan_yanlongkaijia.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyuan_shuofengduzhi.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E9%AD%8F%E5%BB%B6--%E8%AA%93%E6%AD%BB%E5%8D%AB%E6%B1%89.mp4" },
  ],
  "m_shi__xinxianying": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xinxianying_fengzhuluanhui.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xinxianying_jinxiudaimei.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%BE%9B%E5%AE%AA%E8%8B%B1%E3%80%81%E6%8C%A5%E5%BD%A9%E8%BE%A8%E5%BF%83.jpg" },
  ],
  "m_shi__yuji": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_shi__yuji_xingquanjingfu.jpg" },
  ],
  "m_shi__zhonghui": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_shi__zhonghui_qianjiaojitian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/m_shi__zhonghui_qianjiaojitian2.mp4" },
  ],
  "m_sp__caocao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caocao_dihuangkaijia.jpg" },
  ],
  "m_sp__simazhao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_zhaoweihuainan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_denglujiemian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_longxuexuanhuang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_zhaosuyuanxin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_yongduokuishou.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_wenqingliangyuan.jpg" },
  ],
  "m_sp_lord__yuanshu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%A2%81%E6%9C%AF%E3%80%81%E7%99%BB%E6%9E%81%E8%87%B3%E5%B0%8A.mp4" },
  ],
  "m_thoroughbred__zhangliao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangliao_longshengjiuzi.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangliao_benleipozhen.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%AA%A5%E5%BC%A0%E8%BE%BD%E3%80%81%E7%82%B9%E5%A2%A8%E6%83%8A%E9%BE%99.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%AD%8F%E5%BC%A0%E8%BE%BD%E3%80%81%E9%98%B5%E6%96%A9%E8%B9%8B%E9%A1%BF.jpg" },
  ],
  "m_yuan__gaoshun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/gaoshun_cuifengdangyu.jpg" },
  ],
  "m_yuan__sunquan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunquan_songcuichangqing.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E6%9D%83%E3%80%81%E5%90%B4%E7%8E%8B%E5%85%AD%E5%89%91.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E6%9D%83%E3%80%81%E7%BB%98%E9%B8%A2%E9%BB%9B%E6%83%85.mp4" },
  ],
  "maliang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/maliang_dangranyouxin.mp4" },
  ],
  "mazhong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mazhong_gangfengzhuokou.jpg" },
  ],
  "menghuo": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%9F%E8%8E%B7%E3%80%81%E6%96%A7%E8%BF%87%E5%9F%8E%E6%91%A7.mp4" },
  ],
  "mobile2__caomao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mobile2__caomao_xiaolongpoyuan.mp4" },
  ],
  "mobile__baosanniang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/baosanniang_tujiaochunnong.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/baosanniang_satafeishuang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/baosanniang_shenqinggujian.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/images/baosanniang_yanranyixiao.mp4" },
  ],
  "mobile__baoxin": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/baoxin_guanjuetianxia.mp4" },
  ],
  "mobile__bianfuren": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/ol__bianfuren_yindaizhuangmei.mp4" },
  ],
  "mobile__caomao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mobile__caomao_xiaolongpoyuan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caomao_longxuexuanhuang.mp4" },
  ],
  "mobile__caosong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mobile__caosong_yanyinggaopeng.jpg" },
  ],
  "mobile__caoying": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoying_changyelinxi.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoying_baiquemingchen.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoying_shuiqingzhuoying.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoying_weiyingfengming.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/images/caoying_jinzhiyuye.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E6%9B%B9%E5%A9%B4--%E6%B0%B4%E6%B8%85%E6%BF%AF%E7%BC%A8.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E6%9B%B9%E5%A9%B4--%E6%B5%81%E7%BB%AF%E6%83%8A%E6%BE%9C.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E6%9B%B9%E5%A9%B4--%E9%AD%8F%E6%AD%A6%E9%81%97%E9%A3%8E.mp4" },
  ],
  "mobile__chengui": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/chengui_zhanchangrongyao.mp4" },
  ],
  "mobile__duyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/duyu_yulinbilang.jpg" },
  ],
  "mobile__ganfuren": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E7%94%98%E5%A4%AB%E4%BA%BA--%E4%B9%9E%E5%B7%A7%E6%83%85.mp4" },
  ],
  "mobile__godjiangwei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mobile__godjiangwei_jianyintianlin.mp4" },
  ],
  "mobile__godmachao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godmachao_xunwujinglei.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godmachao_madaogongcheng.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godmachao_leizhuafucang.mp4" },
  ],
  "mobile__godsimayi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godsimayi_jianwangzhilai.mp4" },
  ],
  "mobile__guanyinping": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%85%B3%E9%93%B6%E5%B1%8F%E3%80%81%E5%87%A4%E5%B1%8F%E9%93%B6%E6%9C%88.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%85%B3%E9%93%B6%E5%B1%8F--%E7%83%88%E7%84%B0%E7%82%BD%E9%AD%82.mp4" },
  ],
  "mobile__guozhao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mobile__guozhao_quehanjingfeng.mp4" },
  ],
  "mobile__huaman": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mobile__huaman_lingxiufeiyin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%8A%B1%E9%AC%98%E3%80%81%E8%9B%AE%E5%B8%BC%E8%8B%B1%E9%A3%92.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%8A%B1%E9%AC%98%E3%80%81%E9%94%8B%E4%B8%BD%E9%AC%98%E5%BD%B1.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E8%8A%B1%E9%AC%98--%E4%BE%9D%E5%BF%83%E7%BC%B1%E7%BB%BB.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E8%8A%B1%E9%AC%98--%E6%B2%99%E5%9C%BA%E8%9B%AE%E8%8A%B1.mp4" },
  ],
  "mobile__lingju": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/lingju_xueyingposuo.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/images/lingju_hunqiangmengying.mp4" },
  ],
  "mobile__liuye": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/ol__liuye_fenyantianzheng.mp4" },
  ],
  "mobile__maliang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/maliang_dangranyouxin.mp4" },
  ],
  "mobile__qinghegongzhu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/qinghegongzhu_xinxiangqinghuan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/qinghegongzhu_meiyingyingxin.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/qinghegongzhu_yufeiqionghua.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/qinghegongzhu_qingyaqudou.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/qinghegongzhu_wuyinliyan.mp4" },
  ],
  "mobile__simazhao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_zhaoweihuainan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_denglujiemian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_longxuexuanhuang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_zhaosuyuanxin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_yongduokuishou.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simazhao_wenqingliangyuan.jpg" },
  ],
  "mobile__sunluyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunluyu_huweibobing.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E9%B2%81%E8%82%B2%E3%80%81%E7%89%9B%E5%B9%B4%E7%AB%AF%E5%8D%88.mp4" },
  ],
  "mobile__wangyuanji": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wangyuanji_dieyingpianqian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wangyuanji_wenqingliangyuan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wangyuanji_caiyimanwu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wangyuanji_posuoqiwu.mp4" },
  ],
  "mobile__wenyang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyang_wu_poyukaitian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyang_wei_poyukaitian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyang_shiruowanjun.mp4" },
  ],
  "mobile__xurong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xurong_nuliaohengkong.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xurong_nuliaohengkong2.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xurong_lieyanzhihun.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xurong_zhanhuotianjue.mp4" },
  ],
  "mobile__yanghu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/ol__yanghu_qingshangyimeng.jpg" },
  ],
  "mobile__yanghuiyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yanghuiyu_sheniankuanghuan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yanghuiyu_jingyuhehui.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yanghuiyu_yueyaohuashang.mp4" },
  ],
  "mobile__yuanshu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%A2%81%E6%9C%AF%E3%80%81%E7%99%BB%E6%9E%81%E8%87%B3%E5%B0%8A.mp4" },
  ],
  "mobile__zhangbao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%BC%A0%E5%AE%9D%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
  ],
  "mobile__zhangchangpu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangchangpu_zhanchangrongyao.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%BC%A0%E6%98%8C%E8%92%B2%E3%80%81%E5%A4%9C%E9%98%91%E6%B6%B4%E5%A2%A8.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%BC%A0%E6%98%8C%E8%92%B2%E3%80%81%E5%B1%B1%E6%B2%B3%E4%B8%87%E6%9C%B5.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%BC%A0%E6%98%8C%E8%92%B2%E3%80%81%E8%92%B2%E6%9C%88%E5%BF%B5%E5%85%94.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%BC%A0%E6%98%8C%E8%92%B2%E3%80%81%E9%9D%99%E8%B0%A7%E8%BD%BB%E8%88%9F.mp4" },
  ],
  "mobile__zhangfen": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangfen_bihaihanshan.jpg" },
  ],
  "mobile__zhangqiying": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangqiying_lianyanqingfang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangqiying_suirennianfeng.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/images/zhangqiying_jiyufengnian.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%BC%A0%E7%90%AA%E7%91%9B%E3%80%81%E5%AE%9A%E5%BF%83%E9%94%81%E6%84%8F.mp4" },
  ],
  "mobile__zhouchu": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A4%84--%E4%B9%89%E9%99%A4%E4%B8%89%E5%AE%B3-%E5%90%B4.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A4%84--%E6%93%92%E8%99%8E%E6%8B%BF%E8%9B%9F.mp4" },
  ],
  "mou__caocao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caocao_dihuangkaijia.jpg" },
  ],
  "mou__caopi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mou__caopi_qidangshanhe.mp4" },
  ],
  "mou__caoren": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoren_shusijushou.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoren_duoshuai.jpg" },
  ],
  "mou__daqiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/daqiao_huizhilanxin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/daqiao_chunhuaifuqing.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%A4%A7%E4%B9%94%E3%80%81%E6%B8%85%E8%90%A7%E6%B8%85%E4%B8%BD.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%A4%A7%E4%B9%94%E3%80%81%E8%8A%B1%E5%80%9A%E8%BD%BB%E6%B6%9F.jpg" },
  ],
  "mou__diaochan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_taotaolejin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_wuhuoqunxin.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sp__diaochan_huandieyinghun.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_qiushuiyiren.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%B2%82%E8%9D%89%E3%80%81%E5%87%BA%E6%B0%B4%E5%A6%82%E6%9C%88.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E8%B2%82%E8%9D%89--%E7%A7%8B%E6%B0%B4%E4%BC%8A%E4%BA%BA.mp4" },
  ],
  "mou__fazheng": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/fazheng_fengguqingyu.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/fazheng_weijiguangsha.jpg" },
  ],
  "mou__gaoshun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/gaoshun_cuifengdangyu.jpg" },
  ],
  "mou__guohuai": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%83%AD%E6%B7%AE%E3%80%81%E7%B4%AB%E7%94%B5%E9%9C%86%E5%87%BB.jpg" },
  ],
  "mou__guojia": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guojia_yishenzhengdao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/guojia_modianjiangshan.mp4" },
  ],
  "mou__huanggai": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huanggai_hubenguanyong.jpg" },
  ],
  "mou__huangyueying": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_zhifeiqiaohui.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_zhengmianduijue.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_miaoxiangshenji.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangyueying_muniuliuma.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%BB%84%E6%9C%88%E8%8B%B1%E3%80%81%E6%98%8E%E8%89%AF%E5%8D%83%E5%8F%A4.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%BB%84%E6%9C%88%E8%8B%B1%E3%80%81%E6%99%BA%E5%BF%83%E5%B7%A7%E6%89%8B.mp4" },
  ],
  "mou__huangzhong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangzhong_liejianguanyun.jpg" },
  ],
  "mou__jiangwei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mou__jiangwei_jinlangongzhan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/mou__jiangwei_shouyiwujiang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%A7%9C%E7%BB%B4%E3%80%81%E6%98%9F%E6%B2%B3%E9%BA%92%E9%BA%9F.jpg" },
  ],
  "mou__jiaxu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/jiaxu_mouluanchangan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/jiaxu_dangranyouxin.mp4" },
  ],
  "mou__liubei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liubei_manianxianding.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%88%98%E5%A4%87%E3%80%81%E5%85%AD%E6%98%9F%E8%80%80%E5%B8%9D.mp4" },
  ],
  "mou__liubiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liubiao_jingxianggushou.jpg" },
  ],
  "mou__menghuo": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%9F%E8%8E%B7%E3%80%81%E6%96%A7%E8%BF%87%E5%9F%8E%E6%91%A7.mp4" },
  ],
  "mou__pangtong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/pangtong_duoshuai.jpg" },
  ],
  "mou__sunquan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunquan_songcuichangqing.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E6%9D%83%E3%80%81%E5%90%B4%E7%8E%8B%E5%85%AD%E5%89%91.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E6%9D%83%E3%80%81%E7%BB%98%E9%B8%A2%E9%BB%9B%E6%83%85.mp4" },
  ],
  "mou__sunshangxiang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_niaoyuhuaxiang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_qianhouliangnan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_jiaozoongsanjiang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_jinguoqianying.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E5%B0%9A%E9%A6%99%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%AD%99%E5%B0%9A%E9%A6%99--%E6%88%98%E5%9C%BA%E8%8D%A3%E8%80%80.mp4" },
  ],
  "mou__wolong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wolong_qiruojinlan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wolong_lieyanzhihun.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wolong_huichishanhe.jpg" },
  ],
  "mou__xiahoushi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xiahoushi_liandengyingyue.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xiahoushi_chunyanzhihua.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/images/xiahoushi_fuguachenli.mp4" },
  ],
  "mou__xiaoqiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xiaoqiao_lizhitiancheng.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%B0%8F%E4%B9%94%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%B0%8F%E4%B9%94%E3%80%81%E9%87%87%E8%8E%B2%E6%B1%9F%E5%8D%97.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%B0%8F%E4%B9%94--%E6%A1%82%E6%A2%A6%E5%BC%A6%E6%AD%8C.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%B0%8F%E4%B9%94--%E8%8A%B1%E5%A5%BD%E6%9C%88%E5%9C%86.mp4" },
  ],
  "mou__xuhuang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xuhuang_dangkouzhuojun.jpg" },
  ],
  "mou__xunyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%8D%80%E5%BD%A7%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%8D%80%E5%BD%A7%E3%80%81%E6%9D%BE%E9%9F%B5%E9%BE%99%E7%BF%94.jpg" },
  ],
  "mou__yangwan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/ol__yangwan_huacuhuairou.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E6%9D%A8%E5%A9%89%E3%80%81%E6%98%9F%E5%85%89%E6%B7%91%E5%A9%89.mp4" },
  ],
  "mou__yuanshao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yuanshao_zhanchangrongyao.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yuanshao_wojianjichu1.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yuanshao_wojianjichu2.jpg" },
  ],
  "mou__zhangliao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangliao_longshengjiuzi.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangliao_benleipozhen.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%AD%8F%E5%BC%A0%E8%BE%BD%E3%80%81%E9%98%B5%E6%96%A9%E8%B9%8B%E9%A1%BF.jpg" },
  ],
  "mou__zhaoyun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%B5%B5%E4%BA%91%E3%80%81%E8%9B%87%E5%B9%B4%E4%B8%83%E5%A4%95.mp4" },
  ],
  "mou__zhenji": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_xunitiantuan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_zhanchangjueban.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_qingluoyuelong.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_niunianqingming.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_mingzhuyaoqu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_luoshuishenyun.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_duanruiluoshui.mp4" },
  ],
  "mou__zhouyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhouyu_yaxiangzhenzhu.jpg" },
  ],
  "mou__zhugejin": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugejin_zuolonganlan.jpg" },
  ],
  "mou__zhugeliang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_yizhenqingmeng.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_shanhewuyang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_guozhizhushi.mp4" },
  ],
  "mou__zhuran": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhuran_bingranwuju.mp4" },
  ],
  "mou__zhurong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E7%A5%9D%E8%9E%8D%E3%80%81%E7%9B%9B%E5%A4%8F%E7%B9%81%E8%8C%82.jpg" },
  ],
  "mouxusheng": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xusheng_caodaobige.mp4" },
  ],
  "mxing__fazheng": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/fazheng_fengguqingyu.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/fazheng_weijiguangsha.jpg" },
  ],
  "mxing__huangzhong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/huangzhong_liejianguanyun.jpg" },
  ],
  "mxing__wanglang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E7%8E%8B%E6%9C%97%E3%80%81%E5%A4%84%E5%B0%8A%E5%B1%85%E6%98%BE.jpg" },
  ],
  "mxing__weiyan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/weiyan_yanlongkaijia.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyuan_shuofengduzhi.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E9%AD%8F%E5%BB%B6--%E8%AA%93%E6%AD%BB%E5%8D%AB%E6%B1%89.mp4" },
  ],
  "nanhualaoxian": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/nanhualaoxian_zhuomoshanhe.jpg" },
  ],
  "nos__caoxiu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoxiu_qingfengxilie.jpg" },
  ],
  "nos__fazheng": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/fazheng_fengguqingyu.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/fazheng_weijiguangsha.jpg" },
  ],
  "nos__godzhaoyun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godzhaoyun_linzhenjiuxiao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godzhaoyun_zhanlongzaiye.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godzhaoyun_longtenghuyue.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/godzhaoyun_baizhanjinjia.mp4" },
  ],
  "nos__liru": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liru_lieyanzhihun.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E6%9D%8E%E5%84%92%E3%80%81%E9%B8%A9%E6%9D%80%E5%B0%91%E5%B8%9D.mp4" },
  ],
  "nos__wangyi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wangyi_qingtianxieyu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wangyi_zhanchangrongyao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wangyi_jinguozhanye.mp4" },
  ],
  "nos__xunchen": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xunchen_ximuzhize.jpg" },
  ],
  "nos__zhugezhan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugezhan_fulinchiguo.jpg" },
  ],
  "nos__zhuran": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhuran_bingranwuju.mp4" },
  ],
  "pangtong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/pangtong_duoshuai.jpg" },
  ],
  "qinmi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/qinmi_aoyuluntian.mp4" },
  ],
  "re__bulianshi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/bulianshi_bieheguluan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/bulianshi_qiushuiyiren.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E6%AD%A5%E7%BB%83%E5%B8%88%E3%80%81%E7%BB%98%E9%B8%A2%E9%BB%9B%E6%83%85.mp4" },
  ],
  "re__liubiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liubiao_jingxianggushou.jpg" },
  ],
  "re__xusheng": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xusheng_caodaobige.mp4" },
  ],
  "simayi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/simayi_moudingtianxia.jpg" },
  ],
  "sp__caiwenji": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caiwenji_yishenzhengdao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caiwenji_qiushuiyiren.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sp__caiwenji_jinxiudaimei.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%94%A1%E6%96%87%E5%A7%AC%E3%80%81%E5%B2%81%E7%BB%88%E5%B9%B4%E5%BA%86.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E8%94%A1%E6%96%87%E5%A7%AC--%E5%AF%92%E6%9C%88%E4%BB%99%E8%B8%AA.mp4" },
  ],
  "sp__diaochan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_taotaolejin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_wuhuoqunxin.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sp__diaochan_huandieyinghun.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_qiushuiyiren.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%B2%82%E8%9D%89%E3%80%81%E5%87%BA%E6%B0%B4%E5%A6%82%E6%9C%88.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E8%B2%82%E8%9D%89--%E7%A7%8B%E6%B0%B4%E4%BC%8A%E4%BA%BA.mp4" },
  ],
  "sp__jiaxu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/jiaxu_mouluanchangan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/jiaxu_dangranyouxin.mp4" },
  ],
  "sp__xiahoushi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xiahoushi_liandengyingyue.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xiahoushi_chunyanzhihua.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/images/xiahoushi_fuguachenli.mp4" },
  ],
  "sp__zhangliang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%BC%A0%E6%A2%81%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
  ],
  "starsp__caoren": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoren_shusijushou.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoren_duoshuai.jpg" },
  ],
  "starsp__diaochan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_taotaolejin.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_wuhuoqunxin.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sp__diaochan_huandieyinghun.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/diaochan_qiushuiyiren.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%B2%82%E8%9D%89%E3%80%81%E5%87%BA%E6%B0%B4%E5%A6%82%E6%9C%88.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E8%B2%82%E8%9D%89--%E7%A7%8B%E6%B0%B4%E4%BC%8A%E4%BA%BA.mp4" },
  ],
  "starsp__liubei": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/liubei_manianxianding.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%88%98%E5%A4%87%E3%80%81%E5%85%AD%E6%98%9F%E8%80%80%E5%B8%9D.mp4" },
  ],
  "starsp__zhaoyun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sp__zhaoyun_weimingjinxian.mp4" },
  ],
  "std__yuanshu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%A2%81%E6%9C%AF%E3%80%81%E7%99%BB%E6%9E%81%E8%87%B3%E5%B0%8A.mp4" },
  ],
  "sunjian": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E5%9D%9A%E3%80%81%E6%AD%A6%E7%83%88%E5%BC%80%E7%96%86.jpg" },
  ],
  "sunluban": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunluban_jinzhiyuye.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunluban_yuanchaixianglan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E9%B2%81%E7%8F%AD%E3%80%81%E7%89%9B%E5%B9%B4%E7%AB%AF%E5%8D%88.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E9%B2%81%E7%8F%AD%E3%80%81%E7%8E%89%E9%A2%9C%E5%8F%8C%E5%A8%87.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%AD%99%E9%B2%81%E7%8F%AD--%E6%95%95%E5%B9%BD%E6%98%8E.mp4" },
  ],
  "sunluyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunluyu_huweibobing.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E9%B2%81%E8%82%B2%E3%80%81%E7%89%9B%E5%B9%B4%E7%AB%AF%E5%8D%88.mp4" },
  ],
  "sunquan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunquan_songcuichangqing.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E6%9D%83%E3%80%81%E5%90%B4%E7%8E%8B%E5%85%AD%E5%89%91.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E6%9D%83%E3%80%81%E7%BB%98%E9%B8%A2%E9%BB%9B%E6%83%85.mp4" },
  ],
  "sunru": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunru_mulanhanfang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunru_shenianqingming.mp4" },
  ],
  "sunshangxiang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_niaoyuhuaxiang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_qianhouliangnan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_jiaozoongsanjiang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_jinguoqianying.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E5%B0%9A%E9%A6%99%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%AD%99%E5%B0%9A%E9%A6%99--%E6%88%98%E5%9C%BA%E8%8D%A3%E8%80%80.mp4" },
  ],
  "sx2__caocao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caocao_dihuangkaijia.jpg" },
  ],
  "sx__caocao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caocao_dihuangkaijia.jpg" },
  ],
  "sx__caopi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_dangranyouxin.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_longnianzhongqiu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_weiwangchengdi.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caopi_jiuzuiyeqing.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E6%9B%B9%E4%B8%95%E3%80%81%E5%A8%81%E5%BE%A1%E4%B9%9D%E9%9C%84.jpg" },
  ],
  "sx__caoren": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoren_shusijushou.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoren_duoshuai.jpg" },
  ],
  "sx__guanyinping": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%85%B3%E9%93%B6%E5%B1%8F%E3%80%81%E5%87%A4%E5%B1%8F%E9%93%B6%E6%9C%88.mp4" },
  ],
  "sx__lusu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/lusu_dangranyouxin.jpg" },
  ],
  "sx__sunshangxiang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_niaoyuhuaxiang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_qianhouliangnan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_jiaozoongsanjiang.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/sunshangxiang_jinguoqianying.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%AD%99%E5%B0%9A%E9%A6%99%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%AD%99%E5%B0%9A%E9%A6%99--%E6%88%98%E5%9C%BA%E8%8D%A3%E8%80%80.mp4" },
  ],
  "sx__xunyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%8D%80%E5%BD%A7%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%8D%80%E5%BD%A7%E3%80%81%E6%9D%BE%E9%9F%B5%E9%BE%99%E7%BF%94.jpg" },
  ],
  "sx__zhaoyun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%B5%B5%E4%BA%91%E3%80%81%E8%9B%87%E5%B9%B4%E4%B8%83%E5%A4%95.mp4" },
  ],
  "thunder__yuanshu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%A2%81%E6%9C%AF%E3%80%81%E7%99%BB%E6%9E%81%E8%87%B3%E5%B0%8A.mp4" },
  ],
  "tw__maliang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/maliang_dangranyouxin.mp4" },
  ],
  "wanglang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E7%8E%8B%E6%9C%97%E3%80%81%E5%A4%84%E5%B0%8A%E5%B1%85%E6%98%BE.jpg" },
  ],
  "wangyi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wangyi_qingtianxieyu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wangyi_zhanchangrongyao.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wangyi_jinguozhanye.mp4" },
  ],
  "weiyan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/weiyan_yanlongkaijia.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wenyuan_shuofengduzhi.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E9%AD%8F%E5%BB%B6--%E8%AA%93%E6%AD%BB%E5%8D%AB%E6%B1%89.mp4" },
  ],
  "wolong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wolong_qiruojinlan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wolong_lieyanzhihun.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wolong_huichishanhe.jpg" },
  ],
  "wuguotai": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%90%B4%E5%9B%BD%E5%A4%AA--%E9%87%91%E7%A7%8B%E7%8E%89%E9%9C%B2.mp4" },
  ],
  "wuxian": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/wuxian_jinyunfumian.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%90%B4%E8%8B%8B%E3%80%81%E9%87%91%E7%8E%89%E6%BB%A1%E5%A0%82.mp4" },
  ],
  "xiahoushi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xiahoushi_liandengyingyue.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xiahoushi_chunyanzhihua.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/images/xiahoushi_fuguachenli.mp4" },
  ],
  "xiaoqiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xiaoqiao_lizhitiancheng.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%B0%8F%E4%B9%94%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%B0%8F%E4%B9%94%E3%80%81%E9%87%87%E8%8E%B2%E6%B1%9F%E5%8D%97.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%B0%8F%E4%B9%94--%E6%A1%82%E6%A2%A6%E5%BC%A6%E6%AD%8C.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%B0%8F%E4%B9%94--%E8%8A%B1%E5%A5%BD%E6%9C%88%E5%9C%86.mp4" },
  ],
  "xinxianying": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xinxianying_fengzhuluanhui.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xinxianying_jinxiudaimei.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%BE%9B%E5%AE%AA%E8%8B%B1%E3%80%81%E6%8C%A5%E5%BD%A9%E8%BE%A8%E5%BF%83.jpg" },
  ],
  "xuhuang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xuhuang_dangkouzhuojun.jpg" },
  ],
  "xunyou": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xunyou_yizhanshaochang.jpg" },
  ],
  "xunyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%8D%80%E5%BD%A7%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%8D%80%E5%BD%A7%E3%80%81%E6%9D%BE%E9%9F%B5%E9%BE%99%E7%BF%94.jpg" },
  ],
  "xusheng": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xusheng_caodaobige.mp4" },
  ],
  "xushi": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xushi_sijunshanggan.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/xushi_hongdouxiangsi.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%BE%90%E6%B0%8F%E3%80%81%E4%B8%BA%E5%A4%AB%E5%BC%91%E6%95%8C.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%BE%90%E6%B0%8F--%E5%A6%86%E6%88%90%E6%84%BF%E9%81%82.mp4" },
  ],
  "y13__caoren": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoren_shusijushou.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/caoren_duoshuai.jpg" },
  ],
  "yangbiao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yangbiao_guozhizhushi.mp4" },
  ],
  "yuanshao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yuanshao_zhanchangrongyao.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yuanshao_wojianjichu1.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/yuanshao_wojianjichu2.jpg" },
  ],
  "yuanshu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%A2%81%E6%9C%AF%E3%80%81%E7%99%BB%E6%9E%81%E8%87%B3%E5%B0%8A.mp4" },
  ],
  "zhangbao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%BC%A0%E5%AE%9D%E3%80%81%E5%A4%BA%E5%B8%85.jpg" },
  ],
  "zhangchunhua": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%AD%8F%E5%BC%A0%E6%98%A5%E5%8D%8E%E3%80%81%E4%BC%8A%E4%BA%BA%E7%BB%AE%E6%A2%A6.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%AD%8F%E5%BC%A0%E6%98%A5%E5%8D%8E%E3%80%81%E5%90%8D%E5%B0%86%E6%9D%80.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%AD%8F%E5%BC%A0%E6%98%A5%E5%8D%8E%E3%80%81%E5%AE%A3%E7%A9%86%E5%A4%9C%E8%A2%AD.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%AD%8F%E5%BC%A0%E6%98%A5%E5%8D%8E%E3%80%81%E6%9C%88%E4%B8%8B%E7%91%B6%E6%83%85.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%AD%8F%E5%BC%A0%E6%98%A5%E5%8D%8E%E3%80%81%E7%8E%89%E9%B8%BE%E7%BF%A9%E8%B7%B9.mp4" },
  ],
  "zhangliao": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangliao_longshengjiuzi.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangliao_benleipozhen.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E9%AD%8F%E5%BC%A0%E8%BE%BD%E3%80%81%E9%98%B5%E6%96%A9%E8%B9%8B%E9%A1%BF.jpg" },
  ],
  "zhangsong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E5%BC%A0%E6%9D%BE%E3%80%81%E6%B2%83%E9%B2%A4%E6%B3%BD%E6%B1%89.mp4" },
  ],
  "zhangxiu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangxiu_hubenguanyong.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhangxiu_nucongxinqi.mp4" },
  ],
  "zhaoyun": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%B5%B5%E4%BA%91%E3%80%81%E8%9B%87%E5%B9%B4%E4%B8%83%E5%A4%95.mp4" },
  ],
  "zhenji": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_xunitiantuan.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_zhanchangjueban.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_qingluoyuelong.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_niunianqingming.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_mingzhuyaoqu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_luoshuishenyun.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhenji_duanruiluoshui.mp4" },
  ],
  "zhonghui": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhonghui_zhongxiangguipu.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhonghui_longshenjiuzi.jpg" },
  ],
  "zhoufei": [
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A6%83--%E7%A2%A7%E9%87%8E%E7%AE%9C%E5%A3%B0.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A6%83--%E7%AC%BC%E4%B8%AD%E7%AE%9C%E5%93%8D.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A6%83--%E9%87%91%E6%9E%9D%E7%8E%89%E5%8F%B6.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E5%91%A8%E5%A6%83--%E9%B9%8A%E6%8B%BE%E5%A4%95%E6%83%85.mp4" },
  ],
  "zhouyu": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhouyu_yaxiangzhenzhu.jpg" },
  ],
  "zhugedan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugedan_chouchunjuyi.mp4" },
  ],
  "zhugeguo": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeguo_jinzhiyuye.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeguo_qiushuiyiren.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%AF%B8%E8%91%9B%E6%9E%9C%E3%80%81%E5%85%B0%E8%8D%B7%E8%89%BE%E8%8E%B2.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E8%AF%B8%E8%91%9B%E6%9E%9C%E3%80%81%E8%9B%87%E5%B9%B4%E9%99%90%E5%AE%9A.jpg" },
  ],
  "zhugejin": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugejin_zuolonganlan.jpg" },
  ],
  "zhugeliang": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_yizhenqingmeng.mp4" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_shanhewuyang.jpg" },
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugeliang_guozhizhushi.mp4" },
  ],
  "zhugezhan": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhugezhan_fulinchiguo.jpg" },
  ],
  "zhuran": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/zhuran_bingranwuju.mp4" },
  ],
  "zhurong": [
    { url: "https://cdn.jsdelivr.net/gh/Aated/pic@master/%E7%A5%9D%E8%9E%8D%E3%80%81%E7%9B%9B%E5%A4%8F%E7%B9%81%E8%8C%82.jpg" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E7%A5%9D%E8%9E%8D--%E6%B5%B4%E7%81%AB%E7%84%9A%E5%A4%A9.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E7%A5%9D%E8%9E%8D--%E6%B5%B4%E7%81%AB%E8%9B%AE%E7%A5%9E.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E7%A5%9D%E8%9E%8D--%E7%81%AB%E7%A5%9E%E4%B9%8B%E6%80%92.mp4" },
    { url: "https://cnb.cool/Vanshang-Org/pic/-/git/raw/main/skins/video/%E7%A5%9D%E8%9E%8D--%E8%9B%AE%E7%96%86%E5%90%8C%E5%BE%81.mp4" },
  ],
};

/** Hosts the catalog points at. The circuit breaker keys off these. */
export const SKIN_HOSTS: readonly string[] = ["cdn.jsdelivr.net","cnb.cool"];
