import type { CropDef, ItemDef, ItemId, RecipeDef } from './types.ts';

/** The item catalogue. Prices are base shop prices in coins. Tags feed likes/dislikes and gifts. */
export const ITEMS: ItemDef[] = [
  // crops + seeds
  { id: 'turnip', name: 'Turnip', kind: 'crop', price: 8, description: 'A crisp spring turnip.', tags: ['vegetable', 'rustic'], edible: { hunger: 10 } },
  { id: 'turnip_seed', name: 'Turnip Seeds', kind: 'seed', price: 3, description: 'Sprouts fast in spring.', tags: ['farming'] },
  { id: 'potato', name: 'Potato', kind: 'crop', price: 12, description: 'Hearty and filling.', tags: ['vegetable', 'rustic'], edible: { hunger: 14 } },
  { id: 'potato_seed', name: 'Seed Potatoes', kind: 'seed', price: 5, description: 'Plant in spring.', tags: ['farming'] },
  { id: 'strawberry', name: 'Strawberry', kind: 'crop', price: 20, description: 'Sweet and red.', tags: ['fruit', 'sweet', 'pretty'], edible: { hunger: 8, fun: 5 } },
  { id: 'strawberry_seed', name: 'Strawberry Seeds', kind: 'seed', price: 9, description: 'Keeps fruiting through spring.', tags: ['farming'] },
  { id: 'corn', name: 'Corn', kind: 'crop', price: 14, description: 'Golden summer corn.', tags: ['vegetable', 'rustic'], edible: { hunger: 14 } },
  { id: 'corn_seed', name: 'Corn Seeds', kind: 'seed', price: 6, description: 'Summer and autumn.', tags: ['farming'] },
  { id: 'tomato', name: 'Tomato', kind: 'crop', price: 12, description: 'Sun-warmed.', tags: ['vegetable', 'fresh'], edible: { hunger: 9 } },
  { id: 'tomato_seed', name: 'Tomato Seeds', kind: 'seed', price: 5, description: 'A summer vine.', tags: ['farming'] },
  { id: 'pumpkin', name: 'Pumpkin', kind: 'crop', price: 32, description: 'Enormous and orange.', tags: ['vegetable', 'autumn', 'festive'], edible: { hunger: 20 } },
  { id: 'pumpkin_seed', name: 'Pumpkin Seeds', kind: 'seed', price: 12, description: 'Autumn only.', tags: ['farming'] },
  { id: 'wheat', name: 'Wheat', kind: 'crop', price: 6, description: 'For flour.', tags: ['grain', 'rustic'] },
  { id: 'wheat_seed', name: 'Wheat Seeds', kind: 'seed', price: 2, description: 'Summer and autumn.', tags: ['farming'] },
  { id: 'cabbage', name: 'Cabbage', kind: 'crop', price: 16, description: 'Big leafy cabbage.', tags: ['vegetable'], edible: { hunger: 12 } },
  { id: 'cabbage_seed', name: 'Cabbage Seeds', kind: 'seed', price: 6, description: 'Autumn and winter greens.', tags: ['farming'] },
  { id: 'sunflower', name: 'Sunflower', kind: 'crop', price: 18, description: 'Follows the sun.', tags: ['flower', 'pretty', 'summer'] },
  { id: 'sunflower_seed', name: 'Sunflower Seeds', kind: 'seed', price: 8, description: 'Tall and cheerful.', tags: ['farming'] },
  // foraged
  { id: 'berries', name: 'Wild Berries', kind: 'food', price: 6, description: 'Found in the hedgerows.', tags: ['fruit', 'sweet', 'forage'], edible: { hunger: 7, fun: 2 } },
  { id: 'mushroom', name: 'Mushroom', kind: 'food', price: 9, description: 'Earthy forest mushroom.', tags: ['forage', 'earthy'], edible: { hunger: 6 } },
  { id: 'herbs', name: 'Herbs', kind: 'material', price: 7, description: 'Fragrant leaves for cooking and medicine.', tags: ['forage', 'medicine', 'fresh'] },
  { id: 'wildflower', name: 'Wildflower', kind: 'gift', price: 5, description: 'A bright wild bloom.', tags: ['flower', 'pretty', 'romantic'] },
  { id: 'honey', name: 'Honey', kind: 'food', price: 22, description: 'From the orchard hives.', tags: ['sweet', 'fancy'], edible: { hunger: 6, fun: 4 } },
  { id: 'apple', name: 'Apple', kind: 'food', price: 10, description: 'Orchard apple.', tags: ['fruit', 'fresh'], edible: { hunger: 8 } },
  // fish
  { id: 'trout', name: 'Trout', kind: 'fish', price: 18, description: 'River trout.', tags: ['fish'], edible: { hunger: 12 } },
  { id: 'perch', name: 'Perch', kind: 'fish', price: 12, description: 'Common lake perch.', tags: ['fish'], edible: { hunger: 10 } },
  { id: 'carp', name: 'Carp', kind: 'fish', price: 9, description: 'Big and muddy.', tags: ['fish'], edible: { hunger: 12 } },
  { id: 'salmon', name: 'Salmon', kind: 'fish', price: 30, description: 'Rare in the river.', tags: ['fish', 'fancy'], edible: { hunger: 15 } },
  { id: 'catfish', name: 'Catfish', kind: 'fish', price: 24, description: 'Bites in the rain.', tags: ['fish'], edible: { hunger: 14 } },
  // materials
  { id: 'wood', name: 'Wood', kind: 'material', price: 3, description: 'Chopped timber.', tags: ['building', 'rustic'] },
  { id: 'stone', name: 'Stone', kind: 'material', price: 3, description: 'Quarried stone.', tags: ['building'] },
  { id: 'copper_ore', name: 'Copper Ore', kind: 'ore', price: 10, description: 'Reddish ore from the mine.', tags: ['metal', 'mining'] },
  { id: 'iron_ore', name: 'Iron Ore', kind: 'ore', price: 16, description: 'Heavy and grey.', tags: ['metal', 'mining'] },
  { id: 'gold_ore', name: 'Gold Ore', kind: 'ore', price: 45, description: 'A glint in the dark.', tags: ['metal', 'mining', 'fancy'] },
  { id: 'gem', name: 'Gemstone', kind: 'gift', price: 80, description: 'A cut stone that catches the light.', tags: ['fancy', 'pretty', 'romantic', 'mining'] },
  { id: 'copper_bar', name: 'Copper Bar', kind: 'material', price: 30, description: 'Smelted copper.', tags: ['metal'] },
  { id: 'iron_bar', name: 'Iron Bar', kind: 'material', price: 48, description: 'Smelted iron.', tags: ['metal'] },
  { id: 'flour', name: 'Flour', kind: 'material', price: 10, description: 'Milled wheat.', tags: ['baking'] },
  { id: 'milk', name: 'Milk', kind: 'drink', price: 8, description: 'From the farm cows.', tags: ['farm', 'fresh'], edible: { hunger: 5, energy: 3 } },
  { id: 'egg', name: 'Egg', kind: 'food', price: 6, description: 'From the farm hens.', tags: ['farm'], edible: { hunger: 6 } },
  { id: 'wool', name: 'Wool', kind: 'material', price: 14, description: 'Sheared from the sheep.', tags: ['farm', 'soft'] },
  { id: 'cloth', name: 'Cloth', kind: 'material', price: 30, description: 'Woven wool.', tags: ['soft', 'crafting'] },
  // food & drink
  { id: 'bread', name: 'Bread', kind: 'food', price: 12, description: 'Warm from the bakery.', tags: ['baked', 'rustic', 'comfort'], edible: { hunger: 22, energy: 4 } },
  { id: 'sweet_roll', name: 'Sweet Roll', kind: 'food', price: 18, description: 'Cerys’ famous sticky roll.', tags: ['baked', 'sweet', 'comfort'], edible: { hunger: 16, fun: 8 } },
  { id: 'berry_pie', name: 'Berry Pie', kind: 'food', price: 40, description: 'A whole pie.', tags: ['baked', 'sweet', 'fancy', 'festive'], edible: { hunger: 30, fun: 12 } },
  { id: 'stew', name: 'Hearty Stew', kind: 'food', price: 26, description: 'Tavern stew, steaming.', tags: ['cooked', 'comfort', 'rustic'], edible: { hunger: 40, energy: 10 } },
  { id: 'fish_soup', name: 'Fish Soup', kind: 'food', price: 24, description: 'Dov’s recipe.', tags: ['cooked', 'fish', 'comfort'], edible: { hunger: 32, health: 5 } },
  { id: 'roast_veg', name: 'Roast Vegetables', kind: 'food', price: 20, description: 'Crisp at the edges.', tags: ['cooked', 'vegetable'], edible: { hunger: 28 } },
  { id: 'omelette', name: 'Omelette', kind: 'food', price: 16, description: 'Fluffy.', tags: ['cooked', 'farm'], edible: { hunger: 24, energy: 6 } },
  { id: 'ale', name: 'Ale', kind: 'drink', price: 8, description: 'The Drowsy Owl’s own.', tags: ['drink', 'tavern', 'social'], edible: { hunger: 4, fun: 10 } },
  { id: 'cider', name: 'Cider', kind: 'drink', price: 10, description: 'Orchard cider.', tags: ['drink', 'sweet', 'social'], edible: { hunger: 4, fun: 9 } },
  { id: 'tea', name: 'Herbal Tea', kind: 'drink', price: 6, description: 'Calming.', tags: ['drink', 'calm', 'medicine'], edible: { hunger: 2, energy: 5, health: 2 } },
  { id: 'coffee', name: 'Coffee', kind: 'drink', price: 9, description: 'Bitter and bracing.', tags: ['drink', 'morning'], edible: { hunger: 2, energy: 18 } },
  // medicine
  { id: 'tonic', name: 'Herbal Tonic', kind: 'medicine', price: 25, description: 'Elin’s remedy for colds.', tags: ['medicine'], edible: { hunger: 0, health: 25 } },
  { id: 'bandage', name: 'Bandage', kind: 'medicine', price: 10, description: 'Clean linen.', tags: ['medicine'] },
  // tools & crafted
  { id: 'hoe', name: 'Hoe', kind: 'tool', price: 60, description: 'Tills soil.', tags: ['tool', 'farming'] },
  { id: 'watering_can', name: 'Watering Can', kind: 'tool', price: 45, description: 'Waters crops.', tags: ['tool', 'farming'] },
  { id: 'fishing_rod', name: 'Fishing Rod', kind: 'tool', price: 70, description: 'Jory carved the handle.', tags: ['tool', 'fish'] },
  { id: 'pickaxe', name: 'Pickaxe', kind: 'tool', price: 90, description: 'Breaks rock.', tags: ['tool', 'mining', 'metal'] },
  { id: 'axe', name: 'Axe', kind: 'tool', price: 80, description: 'Fells trees.', tags: ['tool', 'metal'] },
  { id: 'horseshoe', name: 'Horseshoe', kind: 'misc', price: 20, description: 'Lucky, some say.', tags: ['metal', 'superstition', 'rustic'] },
  { id: 'lantern', name: 'Lantern', kind: 'furniture', price: 35, description: 'Warm light for a porch.', tags: ['cozy', 'metal', 'crafting'] },
  { id: 'chair', name: 'Oak Chair', kind: 'furniture', price: 55, description: 'Jory’s joinery.', tags: ['cozy', 'crafting', 'rustic'] },
  { id: 'bookshelf', name: 'Bookshelf', kind: 'furniture', price: 120, description: 'Holds a life’s reading.', tags: ['cozy', 'books', 'crafting'] },
  { id: 'birdhouse', name: 'Birdhouse', kind: 'furniture', price: 30, description: 'For the wrens.', tags: ['cozy', 'nature', 'crafting'] },
  // gifts, books, misc
  { id: 'book', name: 'Book', kind: 'book', price: 28, description: 'A well-thumbed volume.', tags: ['books', 'lore'] },
  { id: 'poetry', name: 'Book of Poems', kind: 'book', price: 34, description: 'Verses about the river.', tags: ['books', 'romantic', 'lore'] },
  { id: 'map_fragment', name: 'Old Map Fragment', kind: 'misc', price: 50, description: 'Half of something.', tags: ['mystery', 'lore'] },
  { id: 'pearl', name: 'River Pearl', kind: 'gift', price: 90, description: 'Found in a clam.', tags: ['fancy', 'pretty', 'romantic', 'fish'] },
  { id: 'scarf', name: 'Knitted Scarf', kind: 'gift', price: 40, description: 'Soft wool, warm colours.', tags: ['soft', 'cozy', 'romantic'] },
  { id: 'toy_boat', name: 'Toy Boat', kind: 'gift', price: 22, description: 'Carved from driftwood.', tags: ['crafting', 'playful', 'fish'] },
  { id: 'candle', name: 'Beeswax Candle', kind: 'gift', price: 15, description: 'Smells of honey.', tags: ['cozy', 'sweet'] },
  { id: 'pie_tin', name: 'Pie Tin', kind: 'misc', price: 14, description: 'Bakery equipment.', tags: ['baking', 'metal'] },
  { id: 'nails', name: 'Nails', kind: 'material', price: 5, description: 'A pouch of iron nails.', tags: ['metal', 'building'] },
  { id: 'fertiliser', name: 'Fertiliser', kind: 'material', price: 12, description: 'Makes crops grow faster.', tags: ['farming'] },
];

export const ITEM_BY_ID: Record<ItemId, ItemDef> = Object.fromEntries(ITEMS.map((i) => [i.id, i]));
export const item = (id: ItemId): ItemDef => ITEM_BY_ID[id] ?? { id, name: id, kind: 'misc', price: 1, description: '', tags: [] };

export const CROPS: CropDef[] = [
  { id: 'turnip', seed: 'turnip_seed', name: 'Turnip', seasons: ['spring'], days: 3, yieldQty: 1, stages: 4 },
  { id: 'potato', seed: 'potato_seed', name: 'Potato', seasons: ['spring'], days: 5, yieldQty: 2, stages: 5 },
  { id: 'strawberry', seed: 'strawberry_seed', name: 'Strawberry', seasons: ['spring'], days: 6, yieldQty: 2, regrowDays: 3, stages: 5 },
  { id: 'corn', seed: 'corn_seed', name: 'Corn', seasons: ['summer', 'autumn'], days: 7, yieldQty: 1, regrowDays: 3, stages: 5 },
  { id: 'tomato', seed: 'tomato_seed', name: 'Tomato', seasons: ['summer'], days: 6, yieldQty: 2, regrowDays: 3, stages: 5 },
  { id: 'wheat', seed: 'wheat_seed', name: 'Wheat', seasons: ['summer', 'autumn'], days: 4, yieldQty: 2, stages: 4 },
  { id: 'sunflower', seed: 'sunflower_seed', name: 'Sunflower', seasons: ['summer', 'autumn'], days: 5, yieldQty: 1, stages: 4 },
  { id: 'pumpkin', seed: 'pumpkin_seed', name: 'Pumpkin', seasons: ['autumn'], days: 8, yieldQty: 1, stages: 5 },
  { id: 'cabbage', seed: 'cabbage_seed', name: 'Cabbage', seasons: ['autumn', 'winter'], days: 6, yieldQty: 1, stages: 4 },
];
export const CROP_BY_ID: Record<ItemId, CropDef> = Object.fromEntries(CROPS.map((c) => [c.id, c]));
export const CROP_BY_SEED: Record<ItemId, CropDef> = Object.fromEntries(CROPS.map((c) => [c.seed, c]));

export const RECIPES: RecipeDef[] = [
  { id: 'bread', name: 'Bread', result: { id: 'bread', qty: 2 }, inputs: [{ id: 'flour', qty: 1 }], station: 'oven', minutes: 40 },
  { id: 'sweet_roll', name: 'Sweet Roll', result: { id: 'sweet_roll', qty: 2 }, inputs: [{ id: 'flour', qty: 1 }, { id: 'honey', qty: 1 }], station: 'oven', minutes: 45, skill: { name: 'cooking', level: 2 } },
  { id: 'berry_pie', name: 'Berry Pie', result: { id: 'berry_pie', qty: 1 }, inputs: [{ id: 'flour', qty: 1 }, { id: 'berries', qty: 3 }], station: 'oven', minutes: 60, skill: { name: 'cooking', level: 3 } },
  { id: 'stew', name: 'Hearty Stew', result: { id: 'stew', qty: 3 }, inputs: [{ id: 'potato', qty: 2 }, { id: 'herbs', qty: 1 }], station: 'kitchen', minutes: 50 },
  { id: 'fish_soup', name: 'Fish Soup', result: { id: 'fish_soup', qty: 2 }, inputs: [{ id: 'perch', qty: 1 }, { id: 'herbs', qty: 1 }], station: 'kitchen', minutes: 40 },
  { id: 'roast_veg', name: 'Roast Vegetables', result: { id: 'roast_veg', qty: 2 }, inputs: [{ id: 'turnip', qty: 1 }, { id: 'potato', qty: 1 }], station: 'kitchen', minutes: 35 },
  { id: 'omelette', name: 'Omelette', result: { id: 'omelette', qty: 1 }, inputs: [{ id: 'egg', qty: 2 }], station: 'kitchen', minutes: 15 },
  { id: 'tea', name: 'Herbal Tea', result: { id: 'tea', qty: 2 }, inputs: [{ id: 'herbs', qty: 1 }], station: 'kitchen', minutes: 10 },
  { id: 'cider', name: 'Cider', result: { id: 'cider', qty: 3 }, inputs: [{ id: 'apple', qty: 4 }], station: 'kitchen', minutes: 60 },
  { id: 'flour', name: 'Flour', result: { id: 'flour', qty: 2 }, inputs: [{ id: 'wheat', qty: 3 }], station: 'anywhere', minutes: 20 },
  { id: 'tonic', name: 'Herbal Tonic', result: { id: 'tonic', qty: 1 }, inputs: [{ id: 'herbs', qty: 2 }, { id: 'honey', qty: 1 }], station: 'kitchen', minutes: 30, skill: { name: 'medicine', level: 1 } },
  { id: 'copper_bar', name: 'Copper Bar', result: { id: 'copper_bar', qty: 1 }, inputs: [{ id: 'copper_ore', qty: 3 }], station: 'forge', minutes: 30 },
  { id: 'iron_bar', name: 'Iron Bar', result: { id: 'iron_bar', qty: 1 }, inputs: [{ id: 'iron_ore', qty: 3 }], station: 'forge', minutes: 40 },
  { id: 'nails', name: 'Nails', result: { id: 'nails', qty: 4 }, inputs: [{ id: 'iron_bar', qty: 1 }], station: 'forge', minutes: 20 },
  { id: 'horseshoe', name: 'Horseshoe', result: { id: 'horseshoe', qty: 2 }, inputs: [{ id: 'iron_bar', qty: 1 }], station: 'forge', minutes: 30 },
  { id: 'pickaxe', name: 'Pickaxe', result: { id: 'pickaxe', qty: 1 }, inputs: [{ id: 'iron_bar', qty: 2 }, { id: 'wood', qty: 2 }], station: 'forge', minutes: 90, skill: { name: 'crafting', level: 2 } },
  { id: 'axe', name: 'Axe', result: { id: 'axe', qty: 1 }, inputs: [{ id: 'iron_bar', qty: 1 }, { id: 'wood', qty: 2 }], station: 'forge', minutes: 70, skill: { name: 'crafting', level: 2 } },
  { id: 'lantern', name: 'Lantern', result: { id: 'lantern', qty: 1 }, inputs: [{ id: 'copper_bar', qty: 1 }, { id: 'candle', qty: 1 }], station: 'forge', minutes: 45 },
  { id: 'chair', name: 'Oak Chair', result: { id: 'chair', qty: 1 }, inputs: [{ id: 'wood', qty: 4 }, { id: 'nails', qty: 1 }], station: 'workbench', minutes: 60 },
  { id: 'bookshelf', name: 'Bookshelf', result: { id: 'bookshelf', qty: 1 }, inputs: [{ id: 'wood', qty: 8 }, { id: 'nails', qty: 2 }], station: 'workbench', minutes: 120, skill: { name: 'crafting', level: 3 } },
  { id: 'birdhouse', name: 'Birdhouse', result: { id: 'birdhouse', qty: 1 }, inputs: [{ id: 'wood', qty: 3 }], station: 'workbench', minutes: 40 },
  { id: 'toy_boat', name: 'Toy Boat', result: { id: 'toy_boat', qty: 1 }, inputs: [{ id: 'wood', qty: 2 }], station: 'workbench', minutes: 35 },
  { id: 'fishing_rod', name: 'Fishing Rod', result: { id: 'fishing_rod', qty: 1 }, inputs: [{ id: 'wood', qty: 3 }, { id: 'cloth', qty: 1 }], station: 'workbench', minutes: 60 },
  { id: 'cloth', name: 'Cloth', result: { id: 'cloth', qty: 1 }, inputs: [{ id: 'wool', qty: 2 }], station: 'anywhere', minutes: 40 },
  { id: 'scarf', name: 'Knitted Scarf', result: { id: 'scarf', qty: 1 }, inputs: [{ id: 'wool', qty: 3 }], station: 'anywhere', minutes: 80 },
  { id: 'candle', name: 'Beeswax Candle', result: { id: 'candle', qty: 2 }, inputs: [{ id: 'honey', qty: 1 }], station: 'anywhere', minutes: 25 },
  { id: 'bandage', name: 'Bandage', result: { id: 'bandage', qty: 3 }, inputs: [{ id: 'cloth', qty: 1 }], station: 'anywhere', minutes: 15 },
];
export const RECIPE_BY_ID: Record<string, RecipeDef> = Object.fromEntries(RECIPES.map((r) => [r.id, r]));
