/**
 * What this build could possibly show us.
 *
 * A coverage number without a denominator is a boast. "17 generals played" is
 * only meaningful next to "of the 25 this build ships", and the only way that
 * denominator stays true is to read it out of the build under test rather than
 * to write it down here — `overview.json` is generated by
 * `scripts/build-overview.mjs` from the same Lua the game loads, so a general
 * added to the package appears in the target automatically and immediately
 * shows up as a gap.
 *
 * The request table below is the part that cannot be derived, so it carries its
 * evidence. Separating "we have not covered this yet" from "this build cannot
 * do this" is the difference between a coverage report that shrinks and one
 * that never can — a report that keeps promising to reach a request with no
 * call site is lying about its own ceiling.
 *
 * That cuts both ways, and it did. `AskForPoxi`, `AskForChoices`,
 * `AskForCardsAndChoice`, `AskForMoveCardInBoard` and `AskForArrangeCards` were
 * all filed as "cannot occur", correctly, for the four standard packages. The
 * mobile pack supplies callers for every one of them, and the report went on
 * printing "cannot occur in this build" directly underneath "sent by the engine
 * but never answered here". Each entry now says which generals produce it, so
 * the next package to land is checked against this list rather than against a
 * claim that has quietly expired.
 */

/**
 * Request types, by whether play can produce them at all.
 *
 * `producer` is what to steer toward for the reachable ones; `why` is the
 * evidence for the unreachable ones, quoted from the engine tree the bundle is
 * built from (`FK_ROOT`, default `~/FreeKill`) as of bundle b9a788122678dc43.
 */
export const REQUESTS = {
  /* --------------------------------------------------- reachable in play */
  PlayCard: { reach: 'core', producer: 'every play phase' },
  AskForUseCard: { reach: 'core', producer: 'slash/jink/peach prompts' },
  AskForResponseCard: { reach: 'core', producer: 'response prompts' },
  AskForSkillInvoke: { reach: 'core', producer: 'any optional skill' },
  AskForGeneral: { reach: 'core', producer: 'the pick-your-general dialog' },
  AskForCardChosen: { reach: 'common', producer: 'snatch/dismantlement/fankui' },
  AskForUseActiveSkill: {
    reach: 'common',
    producer: 'phase_discard, plus guicai(simayi), ganglie(xiahoudun), '
      + 'tuxi(zhangliao), liuli(daqiao), yiji(guojia), axe/double_swords/fire_attack',
  },
  AskForAG: {
    reach: 'rare',
    producer: 'the card amazing_grace (五谷丰登), ids 83/84',
    wantCards: ['amazing_grace'],
  },
  AskForGuanxing: {
    reach: 'rare',
    producer: 'the skill guanxing — only general zhugeliang, at the start of his turn',
    wantGenerals: ['zhugeliang'],
    wantSkills: ['guanxing'],
  },
  AskForChoice: {
    reach: 'rare',
    producer: 'the skill fanjian — only general zhouyu',
    wantGenerals: ['zhouyu'],
    wantSkills: ['fanjian'],
    // src/contract/scene.ts marks this `exercised: false` with the comment
    // "unreachable in v1 content". It is reachable; zhouyu's fanjian asks a
    // four-way suit choice every time it is used.
    note: 'src/contract/scene.ts calls this unreachable; it is not',
  },

  /* ------------------ reachable only because the mobile pack supplies callers */
  AskForPoxi: {
    reach: 'rare',
    producer: 'a poxi method — 20 mobile generals; mobile registers five methods '
      + '(zhenxing, changshi__kuiji, daozhuan, AskForCardsChosen, '
      + 'askforCardsChosenFromAreas)',
    note: 'PoxiBox exists and had never run against a real payload — '
      + 'src/contract/scene.ts still marks it exercised:false, which is now the '
      + 'stale claim. Answering it needs more than one card picked: the driver '
      + 'used to click once, leave OK correctly disabled, and report a FAIL '
      + 'against a working room. See policy.mjs.',
  },
  /*
   * Everything below said "no caller in any loaded package", and that was true
   * of standard/standard_cards/maneuvering/test. The mobile pack supplies the
   * callers. These four have been SEEN in a campaign, so they are reachable as
   * a matter of observation, not inference — leaving them classified as
   * unreachable made the report print "cannot occur in this build" directly
   * underneath "sent by the engine but never answered here".
   */
  AskForChoices: {
    reach: 'rare',
    producer: 'askToChoices — 10 mobile generals, e.g. m_yuan__sunquan, majun',
    note: 'sent and answered in a 14-game campaign.',
  },
  AskForCardsAndChoice: {
    reach: 'rare',
    producer: 'askToChooseCardsAndChoice / askToViewCardsAndChoice — 4 mobile '
      + 'generals: m_shi__xinxianying, m_sp__simazhao, ruanhui, mobile__chengui',
    note: 'SENT AND UNANSWERABLE. DialogHost has no case for it, so the room '
      + 'falls through to UnknownRequest and the seat has nothing to click; the '
      + 'campaign reports it as a liveness FAIL. Highest-value dialog to build '
      + 'after AskForMoveCardInBoard.',
  },
  AskForMoveCardInBoard: {
    reach: 'rare',
    producer: 'askToMoveCardInBoard / askToChooseToMoveCardInBoard — 7 mobile '
      + 'generals: mobile__lvfan, mobile__yanghong, mobile__cuiyan, '
      + 'm_ex__lingtong, mxing__zhanghe, pangdegong, yangbiao',
    note: 'SENT AND UNANSWERABLE, same as above and affecting more generals. '
      + 'This is the one to build first.',
  },
  AskForArrangeCards: {
    reach: 'rare',
    producer: 'askToArrangeCards — 2 mobile generals: mobile__godjiangwei, '
      + 'mobile__cuilingyi',
    note: 'ArrangeBox exists; not yet seen in a campaign.',
  },
  AskForExchange: {
    reach: 'unreachable',
    why: 'Room:askToExchange still has zero callers, mobile included.',
  },
  AskForCardsChosen: {
    reach: 'unreachable',
    why: 'not a wire command at all — it is a poxi_type string, and reaches the '
      + 'client as AskForPoxi, which IS reachable and is catalogued above.',
  },
  MiniGame: {
    reach: 'unreachable',
    why: 'no package calls Fk:addMiniGame, so Fk.mini_games is empty.',
  },
  CustomDialog: {
    reach: 'unreachable',
    why: 'zero callers, and it expects a QML path the web client has no analogue for.',
  },
};

/** The ones a campaign is entitled to expect. Everything else is out of scope. */
export const REACHABLE_REQUESTS = Object.entries(REQUESTS)
  .filter(([, v]) => v.reach !== 'unreachable').map(([k]) => k);

export const UNREACHABLE_REQUESTS = Object.entries(REQUESTS)
  .filter(([, v]) => v.reach === 'unreachable').map(([k]) => k);

/** Generals worth steering toward because a rare request hangs off them. */
export const GENERALS_UNLOCKING = (() => {
  const m = new Map();
  for (const [cmd, v] of Object.entries(REQUESTS)) {
    for (const g of v.wantGenerals ?? []) {
      m.set(g, [...(m.get(g) ?? []), cmd]);
    }
  }
  return m;
})();

/** Cards worth steering toward for the same reason. */
export const CARDS_UNLOCKING = (() => {
  const m = new Map();
  for (const [cmd, v] of Object.entries(REQUESTS)) {
    for (const c of v.wantCards ?? []) {
      m.set(c, [...(m.get(c) ?? []), cmd]);
    }
  }
  return m;
})();

/**
 * The build's own roster, fetched from the target.
 *
 * Read from the site under test, not from the repo: auditing a deployed URL
 * whose packages differ from the working tree and then reporting coverage
 * against the working tree's roster would quietly report the wrong gaps.
 */
export async function loadRoster(baseUrl) {
  const url = new URL('overview.json', baseUrl).href;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`cannot read the build's roster at ${url}: HTTP ${res.status}`);
  const o = await res.json();
  const generals = (o.generals ?? []).map((g) => g.name).filter(Boolean).sort();
  const cards = (o.cards ?? []).map((c) => c.name).filter(Boolean).sort();
  const skills = [...new Set((o.generals ?? []).flatMap((g) => g.skills ?? []))].sort();
  /**
   * How a skill is tagged in the build's own rules text.
   *
   * It matters for reading a coverage gap honestly. `锁定技` is a compulsory
   * skill and several of those are purely passive — 马术 shortens distance and
   * 奇才 removes a range limit, and neither ever animates an invocation, so
   * they cannot appear in a "skills that fired" tally no matter how many games
   * are played. `主公技` needs its holder to be the lord *and* to have allies
   * of the same kingdom at the table. Counting those against the driver as
   * untested work is how a coverage number stops being able to reach 100% and
   * quietly stops meaning anything.
   */
  const tr = o.translations ?? {};
  const tagOf = (skill) => {
    const text = String(tr[`:${skill}`] ?? '');
    if (text.startsWith('主公技')) return 'lord';
    if (text.startsWith('锁定技')) return 'locked';
    if (text.startsWith('限定技')) return 'limited';
    return 'active';
  };
  const skillTags = Object.fromEntries(skills.map((s) => [s, tagOf(s)]));
  return {
    url,
    packs: o.packs ?? {},
    generals,
    cards,
    skills,
    skillTags,
    /** Titles, so a report can say 诸葛亮 rather than only zhugeliang. */
    titleOf: Object.fromEntries((o.generals ?? []).map((g) => [g.name, g.title ?? g.name])),
    cardTitleOf: Object.fromEntries((o.cards ?? []).map((c) => [c.name, c.title ?? c.name])),
    /** Which general grants which skill; used to explain a coverage gap. */
    generalOfSkill: Object.fromEntries(
      (o.generals ?? []).flatMap((g) => (g.skills ?? []).map((s) => [s, g.name])),
    ),
  };
}
