/* GENERATED by src/room/assets/present/build-present.mjs — do not edit.
 *
 * 9 frames. 45.8 kB of source PNG -> 19.3 kB of WebP.
 *
 * Geometry and filenames only. The images live in `public/present/` and are
 * fetched by URL the first time a present is thrown, so nothing here pulls a
 * byte of art into any chunk.
 */
export interface PresentFrame {
  /** Source under the engine's `image/anim/`. */
  readonly src: string;
  readonly w: number;
  readonly h: number;
  readonly bytes: number;
}

export const PRESENT_FRAMES: Readonly<Record<string, PresentFrame>> = {
  'egg-shot.webp': { src: 'egg/egg.png', w: 65, h: 78, bytes: 1512 },
  'egg-hit1.webp': { src: 'egg/egg1.png', w: 120, h: 115, bytes: 1846 },
  'egg-hit2.webp': { src: 'egg/egg2.png', w: 120, h: 115, bytes: 1866 },
  'egg-hit3.webp': { src: 'egg/egg3.png', w: 120, h: 115, bytes: 1956 },
  'flower-shot.webp': { src: 'flower/egg.png', w: 88, h: 88, bytes: 1712 },
  'flower-hit1.webp': { src: 'flower/egg1.png', w: 120, h: 115, bytes: 2970 },
  'flower-hit2.webp': { src: 'flower/egg2.png', w: 120, h: 115, bytes: 3170 },
  'flower-hit3.webp': { src: 'flower/egg3.png', w: 120, h: 115, bytes: 3588 },
  'flower-star.webp': { src: 'flower/star.png', w: 38, h: 39, bytes: 1096 },
};
