/**
 * One-line thoughts in the villager's voice, keyed by tool. Slots: {target} {place} {item} {weather}
 * {season} {time} {work} {crop} {recipe} {reason} {need}.
 */
export const THOUGHTS: Record<string, string[]> = {
  go_to: ['Off to {place}.', 'Feet, take me to {place}.', 'Might as well head for {place}.', 'I have business at {place}.'],
  wander: ['No plan. Just walking.', 'Let us see what the {time} has in it.', 'A turn around the place clears the head.', 'Nowhere to be, for once.'],
  enter: ['In we go.', 'Warmer inside.', 'Let us see who is in.'],
  leave_building: ['Out into the {weather}.', 'Some air.', 'Enough of these four walls.'],
  follow: ['I will tag along with {target} a while.', 'Where is {target} off to? Let us find out.', 'Company is company.'],
  go_home: ['Home.', 'Back to my own four walls.', 'Home, and the kettle.', 'That is enough of the world for today.'],
  till: ['Good soil wants turning.', 'Every row starts with the hoe.', 'Turn the earth, and the earth turns back.', 'My back will complain. It always does.'],
  plant: ['{crop} in the ground while the weather holds.', 'A seed is a promise. Let us make some.', 'Plant now, eat later.', '{season} seeds, in they go.'],
  water: ['Thirsty rows.', 'Water while the sun is low.', 'They will not water themselves.', 'A can at a time.'],
  harvest: ['Look at them. Ready.', 'This is the good part.', 'In before the crows get ideas.', 'A basket full is a day well spent.'],
  tend_animals: ['The hens will be shouting for me.', 'Cows first, then everything else.', 'They know my step by now.', 'Feed the beasts, then feed myself.'],
  fish: ['The water looks right.', 'Line in. Then patience.', 'Something is biting today, I can feel it.', 'The river does not care what day it is. Neither do I.', 'One more cast.'],
  mine: ['The rock face is waiting.', 'Deeper today.', 'Somewhere down there is the good stuff.', 'Pick, swing, repeat.', 'Grandmother said east. I say east too.'],
  forage: ['The hedgerows will have something.', 'Berries, mushrooms, whatever the forest is giving.', 'Eyes down, basket ready.', 'Free food, if you know where to look.'],
  chop: ['A tree with wood to spare.', 'The yard is low on timber.', 'Axe, tree, wood. Simple.', 'Chop now, build later.'],
  forge: ['Fire up. {recipe} today.', 'Iron does what it is told, if you are firm.', 'The anvil is the only clock I trust.', 'Make it right or make it again.'],
  repair: ['Somebody has been rough with their tools.', 'A fix is quicker than a replacement.', 'Bring it here. I will see to it.'],
  bake: ['Ovens on. {recipe}.', 'The whole village wakes to my ovens.', 'Flour, warmth, patience.', 'Nobody argues with fresh bread.'],
  cook: ['{recipe} for the pot.', 'Something hot, then.', 'A meal is worth making properly.', 'The kitchen will not mind me.'],
  treat: ['{target} is not well. That is my job.', 'A tonic, and rest. Always rest.', 'Let me look at {target} before it gets worse.'],
  check_up: ['A quick look at {target} will not hurt.', 'Prevention costs nothing.', 'Better to ask now than later.'],
  open_shop: ['Shutters up. Customers, come.', 'Open for business.', 'The shelves will not sell themselves.', 'Another day, another till.'],
  close_shop: ['That will do for today.', 'Count the takings, lock the door.', 'Closing time.'],
  restock: ['Shelves are looking thin.', 'Stock up before anyone notices.', 'Empty shelves earn nothing.'],
  set_price: ['A little adjustment.', 'Supply, demand, and me.', 'The sign says what I say it says.'],
  serve_drinks: ['Glasses up. Who is thirsty?', 'The bar does not run itself.', 'Pour, listen, pour again.', 'Every drink is a story waiting to happen.'],
  host_evening: ['Tonight the Owl sings.', 'Let us make an evening of it.', 'Songs, stories, and a round on me.', 'Fill the place. Fill it!'],
  teach: ['{target} could learn a thing or two.', 'Knowledge is for passing on.', 'Watch my hands, {target}.'],
  catalogue_books: ['The shelves want ordering.', 'Every book in its place.', 'Dust, alphabet, silence. Bliss.', 'Somebody has to know where everything is.'],
  write_book: ['A page, if the words come.', 'The history will not write itself.', 'Pen, paper, courage.', 'Just one more paragraph.'],
  build: ['Wood and nails and a bit of will.', 'Something that will outlast me.', 'Measure twice. Or once, honestly.', 'The bandstand starts with one plank.'],
  craft_furniture: ['{recipe}. The wood knows what it wants to be.', 'A chair is a chair until it is a good chair.', 'Sawdust and whistling.'],
  repair_structure: ['Something around here needs fixing. Always does.', 'A loose board is a promise to the next storm.', 'I will see to {place}.'],
  say: ['Might as well say it.', 'Out loud, then.'],
  greet: ['Ah, {target}.', 'Manners cost nothing.', 'A hello for {target}.'],
  chat: ['I could do with a word with {target}.', 'Let us see what {target} has to say.', '{target} looks like they need talking to.', 'A chat with {target}. Why not.', 'Time for a natter with {target}.'],
  gossip: ['{target} will want to hear this.', 'I cannot keep this to myself.', 'Has {target} heard? I bet not.', 'News travels. Let it.'],
  ask: ['I have a question for {target}.', 'Let me just ask {target}.', 'Curious. I will ask.'],
  compliment: ['{target} deserves a kind word.', 'Say something nice. It costs nothing.', 'I noticed. {target} should know I noticed.'],
  tease: ['{target} is asking for it.', 'A little ribbing never hurt anyone.', 'Watch {target}\'s face when I say this.'],
  apologize: ['I was wrong. Time to say so to {target}.', 'This has gone on long enough.', 'Pride is heavy. Put it down.', 'I owe {target} an apology.'],
  argue: ['I have had it with {target}.', 'Somebody needs to say it to {target}\'s face.', 'This is not going to be pleasant.', 'Enough. {target} and I are having words.'],
  comfort: ['{target} looks wretched. I will sit with them.', 'Nobody should have a bad day alone.', 'A kind word for {target}.'],
  invite: ['{target} should come along.', 'Better with company.', 'Ask {target}. Worst they can say is no.'],
  gift: ['{target} will like this. I think.', 'A little something for {target}.', 'It has been sitting in my pocket for days. Time to hand it over.', 'Because {target} deserves it.'],
  propose: ['My heart is going like the anvil.', 'Now or never.', 'Say it. Just say it.'],
  hug: ['{target} looks like they need one.', 'Come here, {target}.', 'Words are not always enough.'],
  dance: ['That tune! I cannot sit still.', 'One dance.', 'The floor is calling.', 'Dancing, then. Why not.'],
  tell_story: ['Have I told them about the time...?', 'Gather round. This is a good one.', 'A story for the room.'],
  play_music: ['A tune for the {time}.', 'My fingers are itching for a song.', 'Music makes the place feel alive.'],
  buy: ['I need {item}.', 'Off to buy {item}.', 'The purse can stretch to {item}.', 'Can\'t do without {item}.'],
  sell: ['Time to turn {item} into coin.', 'Coin for {item}. Fair is fair.', 'Too much {item} sitting around.'],
  trade: ['{target} has what I want. I have what they want.', 'A swap, then.', 'No money need change hands.'],
  pay: ['Debts get paid. Eventually.', '{target} is owed. Here it is.', 'Coins for {target}. Done is done.'],
  haggle: ['That price is nonsense.', 'Surely there is room to talk.', 'Let us see how firm the sign is.'],
  eat: ['Stomach first.', 'Hungry. Fix that.', 'Something to eat before I fall over.', 'Food. Then the world can have me back.'],
  drink: ['A drink would go down nicely.', 'One, to take the edge off.', 'The Owl is calling.', 'Thirsty work, all this.'],
  sleep: ['Bed. Finally.', 'I am done for the day.', 'Tomorrow can have the rest of me.', 'Sleep, before I fall down where I stand.'],
  nap: ['Just forty winks.', 'My eyes are closing on their own.', 'A nap is not laziness. It is strategy.'],
  rest: ['A sit-down.', 'Let the legs have a minute.', 'Rest while I can.'],
  bathe: ['I smell of {work}.', 'A wash. A proper one.', 'Clean, and then human again.'],
  stroll: ['A walk to {place} while the weather is kind.', 'Legs, do something useful.', 'Fresh air at {place}.', 'The {time} is too good to waste indoors.'],
  pray: ['A quiet minute at the shrine.', 'Luck cannot hurt.', 'Somebody up there might be listening.'],
  read: ['A book and a corner.', 'Words, then. Better than people, sometimes.', 'Just a chapter.', 'Lose myself in a page.'],
  garden: ['The garden wants seeing to.', 'Hands in the earth for a bit.', 'Weeds do not weed themselves.'],
  decorate_home: ['{item} will look right by the window.', 'Make the place feel like mine.', 'A house is a home when it has {item} in it.'],
  visit: ['I will call at {place}.', 'See who is at {place}.', 'A visit to {place}, for the company.', 'I have not been to {place} in a while.'],
  watch_stars: ['The sky is clear. Up the hill.', 'Stars. Just stars for a while.', 'The night is too big to sleep through.'],
  swim: ['The lake looks perfect.', 'A swim! While the sun is out.', 'Cold water, hot day.'],
  craft: ['{recipe}, by hand.', 'Idle hands. Fix that.', 'Something to make.'],
  use_item: ['{item}. That should help.', 'Use it or lose it.'],
  pick_up: ['That is worth picking up.', 'Nobody else wants it.'],
  drop: ['I do not need this.', 'Lighten the load.'],
  plant_flower: ['A flower for {place}.', 'Something pretty where people can see it.', 'A little colour never hurt.'],
  look_around: ['Let me see who is about.', 'Where is everyone?', 'Take stock.'],
  check_board: ['What is on the board today?', 'Any news? Any work?', 'The board knows before I do.'],
  check_weather: ['What is the sky doing?', 'Tomorrow looks like {weather}, by the smell of it.', 'Sniff the air. Always.'],
  recall: ['Now what was it...', 'Let me think.'],
  ask_about: ['I wonder what {target} knows.', 'Ask around. Quietly.'],
  set_goal: ['I have decided.', 'A plan, then.', 'Write it on the heart.'],
  remember: ['I will remember that.', 'Worth noting.'],
  plan_day: ['Let me rethink today.', 'New plan.'],
  post_request: ['Somebody in this village must have {item}.', 'Ask and it shall be given. For a price.', 'The board can work for me for once.'],
  accept_request: ['I can do that. And the coin will not hurt.', 'Somebody needs a hand. Here is mine.', 'I know exactly where to get that.'],
  complete_request: ['Delivery. As promised.', 'Here is what they wanted.', 'A promise kept is worth more than the reward. The reward is nice too.'],
  organise_event: ['Let us get people together.', 'The {time} needs an occasion.', 'I will make something happen.'],
  attend_event: ['I would not miss this.', 'Everyone will be there.', 'Off to {place}, then.'],
  idle: ['...', 'Give me a minute.', 'Just thinking.', 'Nothing pressing.'],
};

export const NEED_THOUGHTS: Record<string, string[]> = {
  hunger: ['My stomach has opinions.', 'I could eat a horse. A small one.', 'Food. Priorities.'],
  energy: ['I am dead on my feet.', 'Everything aches.', 'Eyes like lead.'],
  social: ['I have not spoken to a soul all day.', 'Company would be nice.', 'Too quiet, even for me.'],
  fun: ['All work makes for a dull day.', 'I need something that is not work.', 'Boredom is a kind of hunger.'],
  comfort: ['Cold, wet, and fed up.', 'I want a chair and a fire.', 'Everything is damp.'],
  purpose: ['What am I even doing today?', 'I need to get something done.', 'Restless. Work would fix it.'],
};
