/* GENERATED by src/room/assets/anim/build-anim.mjs — do not edit.
 *
 * 37 effects, 436 frames.
 * 17.70 MB of source PNG -> 3324 kB of WebP.
 *
 * Metadata only. The sheets themselves live in `public/anim/` and are fetched
 * the first time an effect plays; nothing here pulls in an image.
 */
export interface AnimSheet {
  /** The name the engine uses — a card name, an `image/anim` name, or
   *  `skillInvoke/<category>`. */
  readonly name: string;
  readonly kind: 'card' | 'common' | 'skill';
  /** Filename under `public/anim/`. */
  readonly file: string;
  readonly frames: number;
  /** One frame's size. The strip is `frames * w` wide. */
  readonly w: number;
  readonly h: number;
  readonly bytes: number;
}

export const ANIM_SHEETS: readonly AnimSheet[] = [
  {
    "name": "analeptic",
    "kind": "card",
    "file": "analeptic.webp",
    "frames": 12,
    "w": 188,
    "h": 184,
    "bytes": 116728
  },
  {
    "name": "axe",
    "kind": "card",
    "file": "axe.webp",
    "frames": 12,
    "w": 230,
    "h": 178,
    "bytes": 46798
  },
  {
    "name": "blade",
    "kind": "card",
    "file": "blade.webp",
    "frames": 12,
    "w": 240,
    "h": 240,
    "bytes": 110066
  },
  {
    "name": "crossbow",
    "kind": "card",
    "file": "crossbow.webp",
    "frames": 12,
    "w": 240,
    "h": 240,
    "bytes": 93720
  },
  {
    "name": "damage",
    "kind": "common",
    "file": "damage.webp",
    "frames": 6,
    "w": 172,
    "h": 170,
    "bytes": 25090
  },
  {
    "name": "double_swords",
    "kind": "card",
    "file": "double_swords.webp",
    "frames": 12,
    "w": 196,
    "h": 240,
    "bytes": 96788
  },
  {
    "name": "eight_diagram",
    "kind": "card",
    "file": "eight_diagram.webp",
    "frames": 12,
    "w": 240,
    "h": 240,
    "bytes": 133684
  },
  {
    "name": "fan",
    "kind": "card",
    "file": "fan.webp",
    "frames": 12,
    "w": 180,
    "h": 222,
    "bytes": 114050
  },
  {
    "name": "fire__slash",
    "kind": "card",
    "file": "fire__slash.webp",
    "frames": 12,
    "w": 188,
    "h": 184,
    "bytes": 150690
  },
  {
    "name": "guding_blade",
    "kind": "card",
    "file": "guding_blade.webp",
    "frames": 12,
    "w": 240,
    "h": 192,
    "bytes": 60994
  },
  {
    "name": "halberd",
    "kind": "card",
    "file": "halberd.webp",
    "frames": 12,
    "w": 218,
    "h": 190,
    "bytes": 86848
  },
  {
    "name": "ice_sword",
    "kind": "card",
    "file": "ice_sword.webp",
    "frames": 12,
    "w": 102,
    "h": 214,
    "bytes": 76622
  },
  {
    "name": "jink",
    "kind": "card",
    "file": "jink.webp",
    "frames": 12,
    "w": 240,
    "h": 240,
    "bytes": 125808
  },
  {
    "name": "judgebad",
    "kind": "common",
    "file": "judgebad.webp",
    "frames": 12,
    "w": 186,
    "h": 156,
    "bytes": 44716
  },
  {
    "name": "judgegood",
    "kind": "common",
    "file": "judgegood.webp",
    "frames": 12,
    "w": 184,
    "h": 146,
    "bytes": 37362
  },
  {
    "name": "kylin_bow",
    "kind": "card",
    "file": "kylin_bow.webp",
    "frames": 12,
    "w": 240,
    "h": 158,
    "bytes": 45610
  },
  {
    "name": "nioh_shield",
    "kind": "card",
    "file": "nioh_shield.webp",
    "frames": 12,
    "w": 198,
    "h": 204,
    "bytes": 97414
  },
  {
    "name": "peach",
    "kind": "card",
    "file": "peach.webp",
    "frames": 12,
    "w": 188,
    "h": 188,
    "bytes": 119856
  },
  {
    "name": "playing",
    "kind": "common",
    "file": "playing.webp",
    "frames": 12,
    "w": 188,
    "h": 240,
    "bytes": 110818
  },
  {
    "name": "qinggang_sword",
    "kind": "card",
    "file": "qinggang_sword.webp",
    "frames": 12,
    "w": 240,
    "h": 240,
    "bytes": 87306
  },
  {
    "name": "selectable",
    "kind": "common",
    "file": "selectable.webp",
    "frames": 10,
    "w": 174,
    "h": 178,
    "bytes": 83424
  },
  {
    "name": "selected",
    "kind": "common",
    "file": "selected.webp",
    "frames": 12,
    "w": 188,
    "h": 240,
    "bytes": 109542
  },
  {
    "name": "silver_lion",
    "kind": "card",
    "file": "silver_lion.webp",
    "frames": 12,
    "w": 212,
    "h": 240,
    "bytes": 104328
  },
  {
    "name": "skillInvoke/control",
    "kind": "skill",
    "file": "skillInvoke-control.webp",
    "frames": 12,
    "w": 222,
    "h": 226,
    "bytes": 120166
  },
  {
    "name": "skillInvoke/defensive",
    "kind": "skill",
    "file": "skillInvoke-defensive.webp",
    "frames": 12,
    "w": 222,
    "h": 226,
    "bytes": 80162
  },
  {
    "name": "skillInvoke/drawcard",
    "kind": "skill",
    "file": "skillInvoke-drawcard.webp",
    "frames": 12,
    "w": 222,
    "h": 226,
    "bytes": 82194
  },
  {
    "name": "skillInvoke/masochism",
    "kind": "skill",
    "file": "skillInvoke-masochism.webp",
    "frames": 12,
    "w": 222,
    "h": 226,
    "bytes": 101202
  },
  {
    "name": "skillInvoke/negative",
    "kind": "skill",
    "file": "skillInvoke-negative.webp",
    "frames": 12,
    "w": 222,
    "h": 226,
    "bytes": 43518
  },
  {
    "name": "skillInvoke/offensive",
    "kind": "skill",
    "file": "skillInvoke-offensive.webp",
    "frames": 12,
    "w": 222,
    "h": 226,
    "bytes": 81476
  },
  {
    "name": "skillInvoke/special",
    "kind": "skill",
    "file": "skillInvoke-special.webp",
    "frames": 12,
    "w": 222,
    "h": 226,
    "bytes": 82590
  },
  {
    "name": "skillInvoke/support",
    "kind": "skill",
    "file": "skillInvoke-support.webp",
    "frames": 12,
    "w": 222,
    "h": 226,
    "bytes": 106058
  },
  {
    "name": "skillInvoke/switch",
    "kind": "skill",
    "file": "skillInvoke-switch.webp",
    "frames": 12,
    "w": 160,
    "h": 160,
    "bytes": 98936
  },
  {
    "name": "slash",
    "kind": "card",
    "file": "slash.webp",
    "frames": 12,
    "w": 188,
    "h": 184,
    "bytes": 81662
  },
  {
    "name": "spear",
    "kind": "card",
    "file": "spear.webp",
    "frames": 12,
    "w": 240,
    "h": 240,
    "bytes": 118548
  },
  {
    "name": "thunder__slash",
    "kind": "card",
    "file": "thunder__slash.webp",
    "frames": 12,
    "w": 188,
    "h": 184,
    "bytes": 120454
  },
  {
    "name": "vine",
    "kind": "card",
    "file": "vine.webp",
    "frames": 12,
    "w": 132,
    "h": 138,
    "bytes": 73866
  },
  {
    "name": "vineburn",
    "kind": "card",
    "file": "vineburn.webp",
    "frames": 12,
    "w": 156,
    "h": 184,
    "bytes": 134834
  }
];

export const ANIM_BY_NAME: ReadonlyMap<string, AnimSheet> =
  new Map(ANIM_SHEETS.map((s) => [s.name, s]));

/** Total transfer cost if every sheet were fetched: 3324 kB. */
export const ANIM_TOTAL_BYTES = 3403928;
